import path from "path"
import CopyPlugin from "copy-webpack-plugin"
import {ZipperPlugin} from "./plugins/ZipperPlugin"
import { baseConfig } from "./webpack.config"
import {WebpackConfiguration} from "webpack-dev-server"

export const prodConfig: WebpackConfiguration = {
  ...baseConfig,
  mode: "production",
  // add the zipper plugin to the list of plugins
  plugins: [
    ...baseConfig.plugins as any[],
    new CopyPlugin({
      patterns: [
        {
          from: "./project/public",
          // prevents the index.html from being copied to the the public folder, as it's going to be
          // generated by webpack
          filter: async (filePath) => {
            return path.basename(filePath) !== "index.html"
          }
        }
      ]
    }),
    new ZipperPlugin()
  ]
}
