import path from "path"
import CopyPlugin from "copy-webpack-plugin"
import { ZipperPlugin } from "./plugins/ZipperPlugin"
import { createBaseConfig, WebpackConfigFactory } from "./webpack.config"
import { CWD_PATH } from "../constants"

export const createProdConfig: WebpackConfigFactory = options => {
  const { srcPath, minify, zippify } = options
  const baseConfig = createBaseConfig(options)
  return {
    ...baseConfig,
    mode: "production",
    optimization: {
      minimize: minify,
    },
    // add the zipper plugin to the list of plugins
    plugins: [
      ...(baseConfig.plugins as any[]),
      new CopyPlugin({
        patterns: [
          {
            from: path.resolve(CWD_PATH, srcPath, "public"),
            // prevents the index.html from being copied to the the public folder, as it's going to be
            // generated by webpack
            filter: async filePath => {
              return path.basename(filePath) !== "index.html"
            },
          },
        ],
      }),
      zippify && new ZipperPlugin({ zipPath: baseConfig.output.path + ".zip" }),
    ].filter(p => !!p),
  }
}
