//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// DutchAuctionV2
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const dutchAuctionV2Abi = [
  {
    type: "constructor",
    inputs: [
      { name: "_owner", internalType: "address", type: "address" },
      { name: "_feeManager", internalType: "address", type: "address" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "", internalType: "address", type: "address" },
      { name: "", internalType: "uint256", type: "uint256" },
    ],
    name: "auctions",
    outputs: [
      { name: "refunded", internalType: "bool", type: "bool" },
      { name: "stepLength", internalType: "uint248", type: "uint248" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "_token", internalType: "address", type: "address" },
      { name: "_reserveId", internalType: "uint256", type: "uint256" },
      { name: "_amount", internalType: "uint256", type: "uint256" },
      { name: "_to", internalType: "address", type: "address" },
    ],
    name: "buy",
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    inputs: [
      { name: "_token", internalType: "address", type: "address" },
      { name: "_reserveId", internalType: "uint256", type: "uint256" },
      { name: "_to", internalType: "address", type: "address" },
      { name: "_indexes", internalType: "uint256[]", type: "uint256[]" },
      { name: "_proofs", internalType: "bytes32[][]", type: "bytes32[][]" },
    ],
    name: "buyAllowlist",
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    inputs: [
      { name: "_token", internalType: "address", type: "address" },
      { name: "_reserveId", internalType: "uint256", type: "uint256" },
      { name: "_amount", internalType: "uint256", type: "uint256" },
      { name: "_to", internalType: "address", type: "address" },
      { name: "_index", internalType: "uint256", type: "uint256" },
      { name: "_signature", internalType: "bytes", type: "bytes" },
    ],
    name: "buyMintPass",
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    inputs: [],
    name: "cancelOwnershipHandover",
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    inputs: [
      { name: "pendingOwner", internalType: "address", type: "address" },
    ],
    name: "completeOwnershipHandover",
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    inputs: [],
    name: "eip712Domain",
    outputs: [
      { name: "fields", internalType: "bytes1", type: "bytes1" },
      { name: "name", internalType: "string", type: "string" },
      { name: "version", internalType: "string", type: "string" },
      { name: "chainId", internalType: "uint256", type: "uint256" },
      { name: "verifyingContract", internalType: "address", type: "address" },
      { name: "salt", internalType: "bytes32", type: "bytes32" },
      { name: "extensions", internalType: "uint256[]", type: "uint256[]" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "feeManager",
    outputs: [{ name: "", internalType: "address", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "_token", internalType: "address", type: "address" },
      { name: "_reserveId", internalType: "uint256", type: "uint256" },
      { name: "_reserveNonce", internalType: "uint256", type: "uint256" },
      { name: "_index", internalType: "uint256", type: "uint256" },
      { name: "_claimer", internalType: "address", type: "address" },
    ],
    name: "generateTypedDataHash",
    outputs: [{ name: "", internalType: "bytes32", type: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [{ name: "_token", internalType: "address", type: "address" }],
    name: "getFirstValidReserve",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [{ name: "_token", internalType: "address", type: "address" }],
    name: "getLatestUpdate",
    outputs: [{ name: "", internalType: "uint40", type: "uint40" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "_token", internalType: "address", type: "address" },
      { name: "_reserveId", internalType: "uint256", type: "uint256" },
    ],
    name: "getPrice",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "", internalType: "address", type: "address" },
      { name: "", internalType: "uint256", type: "uint256" },
    ],
    name: "merkleRoots",
    outputs: [{ name: "", internalType: "bytes32", type: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "", internalType: "address", type: "address" },
      { name: "", internalType: "uint256", type: "uint256" },
    ],
    name: "numberMinted",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "owner",
    outputs: [{ name: "result", internalType: "address", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "pendingOwner", internalType: "address", type: "address" },
    ],
    name: "ownershipHandoverExpiresAt",
    outputs: [{ name: "result", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "pause",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [],
    name: "paused",
    outputs: [{ name: "", internalType: "bool", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "_token", internalType: "address", type: "address" },
      { name: "_reserveId", internalType: "uint256", type: "uint256" },
      { name: "_buyer", internalType: "address", type: "address" },
    ],
    name: "refund",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "", internalType: "address", type: "address" },
      { name: "", internalType: "uint256", type: "uint256" },
    ],
    name: "refunds",
    outputs: [{ name: "lastPrice", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "renounceOwnership",
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    inputs: [],
    name: "requestOwnershipHandover",
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    inputs: [
      { name: "", internalType: "address", type: "address" },
      { name: "", internalType: "uint256", type: "uint256" },
    ],
    name: "reserveNonce",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "", internalType: "address", type: "address" },
      { name: "", internalType: "uint256", type: "uint256" },
    ],
    name: "reserves",
    outputs: [
      { name: "startTime", internalType: "uint64", type: "uint64" },
      { name: "endTime", internalType: "uint64", type: "uint64" },
      { name: "allocation", internalType: "uint128", type: "uint128" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "", internalType: "address", type: "address" },
      { name: "", internalType: "uint256", type: "uint256" },
    ],
    name: "saleProceeds",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [{ name: "_feeManager", internalType: "address", type: "address" }],
    name: "setFeeManager",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      {
        name: "_reserve",
        internalType: "struct ReserveInfo",
        type: "tuple",
        components: [
          { name: "startTime", internalType: "uint64", type: "uint64" },
          { name: "endTime", internalType: "uint64", type: "uint64" },
          { name: "allocation", internalType: "uint128", type: "uint128" },
        ],
      },
      { name: "_mintDetails", internalType: "bytes", type: "bytes" },
    ],
    name: "setMintDetails",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "", internalType: "address", type: "address" },
      { name: "", internalType: "uint256", type: "uint256" },
    ],
    name: "signingAuthorities",
    outputs: [{ name: "", internalType: "address", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [{ name: "newOwner", internalType: "address", type: "address" }],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    inputs: [],
    name: "unpause",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "_token", internalType: "address", type: "address" },
      { name: "_reserveId", internalType: "uint256", type: "uint256" },
    ],
    name: "withdraw",
    outputs: [],
    stateMutability: "nonpayable",
  },
  { type: "event", anonymous: false, inputs: [], name: "EIP712DomainChanged" },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "_prevManager",
        internalType: "address",
        type: "address",
        indexed: false,
      },
      {
        name: "_newManager",
        internalType: "address",
        type: "address",
        indexed: false,
      },
    ],
    name: "FeeManagerSet",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "_token",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "_reserveId",
        internalType: "uint256",
        type: "uint256",
        indexed: true,
      },
      {
        name: "_reserveInfo",
        internalType: "struct ReserveInfo",
        type: "tuple",
        components: [
          { name: "startTime", internalType: "uint64", type: "uint64" },
          { name: "endTime", internalType: "uint64", type: "uint64" },
          { name: "allocation", internalType: "uint128", type: "uint128" },
        ],
        indexed: false,
      },
      {
        name: "_merkleRoot",
        internalType: "bytes32",
        type: "bytes32",
        indexed: false,
      },
      {
        name: "_mintPassSigner",
        internalType: "address",
        type: "address",
        indexed: false,
      },
      {
        name: "_auctionInfo",
        internalType: "struct AuctionInfo",
        type: "tuple",
        components: [
          { name: "refunded", internalType: "bool", type: "bool" },
          { name: "stepLength", internalType: "uint248", type: "uint248" },
          { name: "prices", internalType: "uint256[]", type: "uint256[]" },
        ],
        indexed: false,
      },
    ],
    name: "MintDetailsSet",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "pendingOwner",
        internalType: "address",
        type: "address",
        indexed: true,
      },
    ],
    name: "OwnershipHandoverCanceled",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "pendingOwner",
        internalType: "address",
        type: "address",
        indexed: true,
      },
    ],
    name: "OwnershipHandoverRequested",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "oldOwner",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "newOwner",
        internalType: "address",
        type: "address",
        indexed: true,
      },
    ],
    name: "OwnershipTransferred",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "_token",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "_reserveId",
        internalType: "uint256",
        type: "uint256",
        indexed: true,
      },
      {
        name: "_claimer",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "_index",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "PassClaimed",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "account",
        internalType: "address",
        type: "address",
        indexed: false,
      },
    ],
    name: "Paused",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "_token",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "_reserveId",
        internalType: "uint256",
        type: "uint256",
        indexed: true,
      },
      {
        name: "_buyer",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      { name: "_to", internalType: "address", type: "address", indexed: false },
      {
        name: "_amount",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
      {
        name: "_price",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
      {
        name: "_platformFee",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
      {
        name: "_mintFee",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
      {
        name: "_splitAmount",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "Purchase",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "_token",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "_reserveId",
        internalType: "uint256",
        type: "uint256",
        indexed: true,
      },
      {
        name: "_buyer",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "_refundAmount",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "RefundClaimed",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "_token",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "_reserveId",
        internalType: "uint256",
        type: "uint256",
        indexed: true,
      },
      {
        name: "_claimer",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "_index",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "SlotClaimed",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "account",
        internalType: "address",
        type: "address",
        indexed: false,
      },
    ],
    name: "Unpaused",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "_token",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "_reserveId",
        internalType: "uint256",
        type: "uint256",
        indexed: true,
      },
      {
        name: "_creator",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "_proceeds",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "Withdrawn",
  },
  { type: "error", inputs: [], name: "AddressZero" },
  { type: "error", inputs: [], name: "InsufficientFunds" },
  { type: "error", inputs: [], name: "InsufficientPrice" },
  { type: "error", inputs: [], name: "InvalidAllocation" },
  { type: "error", inputs: [], name: "InvalidAmount" },
  { type: "error", inputs: [], name: "InvalidPayment" },
  { type: "error", inputs: [], name: "InvalidPrice" },
  { type: "error", inputs: [], name: "InvalidPriceCurve" },
  { type: "error", inputs: [], name: "InvalidProof" },
  { type: "error", inputs: [], name: "InvalidReserve" },
  { type: "error", inputs: [], name: "InvalidShortString" },
  { type: "error", inputs: [], name: "InvalidSignature" },
  { type: "error", inputs: [], name: "InvalidStep" },
  { type: "error", inputs: [], name: "InvalidToken" },
  { type: "error", inputs: [], name: "NewOwnerIsZeroAddress" },
  { type: "error", inputs: [], name: "NoAllowlist" },
  { type: "error", inputs: [], name: "NoHandoverRequest" },
  { type: "error", inputs: [], name: "NoPublicMint" },
  { type: "error", inputs: [], name: "NoRefund" },
  { type: "error", inputs: [], name: "NoSigningAuthority" },
  { type: "error", inputs: [], name: "NonRefundableDA" },
  { type: "error", inputs: [], name: "NotEnded" },
  { type: "error", inputs: [], name: "NotStarted" },
  { type: "error", inputs: [], name: "OnlyAuthorityOrAllowlist" },
  { type: "error", inputs: [], name: "PassAlreadyClaimed" },
  { type: "error", inputs: [], name: "PricesOutOfOrder" },
  { type: "error", inputs: [], name: "SlotAlreadyClaimed" },
  {
    type: "error",
    inputs: [{ name: "str", internalType: "string", type: "string" }],
    name: "StringTooLong",
  },
  { type: "error", inputs: [], name: "Unauthorized" },
] as const

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// FxAirdrop
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const fxAirdropAbi = [
  {
    type: "constructor",
    inputs: [
      { name: "_owner", internalType: "address", type: "address" },
      { name: "_fxToken", internalType: "address", type: "address" },
      { name: "_merkleRoot", internalType: "bytes32", type: "bytes32" },
      { name: "_lockTime", internalType: "uint256", type: "uint256" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "_amount", internalType: "uint256", type: "uint256" },
      { name: "_merkleProof", internalType: "bytes32[]", type: "bytes32[]" },
    ],
    name: "claim",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "_user", internalType: "address", type: "address" },
      { name: "_amount", internalType: "uint256", type: "uint256" },
      { name: "_merkleProof", internalType: "bytes32[]", type: "bytes32[]" },
    ],
    name: "claimFor",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "_to", internalType: "address", type: "address" },
      { name: "_amount", internalType: "uint256", type: "uint256" },
      { name: "_merkleProof", internalType: "bytes32[]", type: "bytes32[]" },
    ],
    name: "claimTo",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [],
    name: "fxToken",
    outputs: [{ name: "", internalType: "address", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [{ name: "", internalType: "address", type: "address" }],
    name: "hasClaimed",
    outputs: [{ name: "", internalType: "bool", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "lockTimestamp",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "merkleRoot",
    outputs: [{ name: "", internalType: "bytes32", type: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "owner",
    outputs: [{ name: "", internalType: "address", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "renounceOwnership",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [{ name: "newOwner", internalType: "address", type: "address" }],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "_newTimestamp", internalType: "uint256", type: "uint256" },
    ],
    name: "updateLockTimestamp",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [{ name: "_newRoot", internalType: "bytes32", type: "bytes32" }],
    name: "updateMerkleRoot",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [{ name: "_to", internalType: "address", type: "address" }],
    name: "withdraw",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      { name: "user", internalType: "address", type: "address", indexed: true },
      {
        name: "amount",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "AirdropClaimed",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "newTimestamp",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "LockTimestampUpdated",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "newRoot",
        internalType: "bytes32",
        type: "bytes32",
        indexed: false,
      },
    ],
    name: "MerkleRootUpdated",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "previousOwner",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "newOwner",
        internalType: "address",
        type: "address",
        indexed: true,
      },
    ],
    name: "OwnershipTransferred",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      { name: "to", internalType: "address", type: "address", indexed: false },
      {
        name: "amount",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "Withdrawal",
  },
  { type: "error", inputs: [], name: "FxAirdrop__AlreadyClaimed" },
  { type: "error", inputs: [], name: "FxAirdrop__InvalidProof" },
  { type: "error", inputs: [], name: "FxAirdrop__LockTimeElapsed" },
  { type: "error", inputs: [], name: "FxAirdrop__LockTimeNotElapsed" },
  { type: "error", inputs: [], name: "FxAirdrop__ZeroAmount" },
  {
    type: "error",
    inputs: [{ name: "owner", internalType: "address", type: "address" }],
    name: "OwnableInvalidOwner",
  },
  {
    type: "error",
    inputs: [{ name: "account", internalType: "address", type: "address" }],
    name: "OwnableUnauthorizedAccount",
  },
  {
    type: "error",
    inputs: [{ name: "token", internalType: "address", type: "address" }],
    name: "SafeERC20FailedOperation",
  },
] as const

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// PumpFun
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const pumpFunAbi = [
  {
    type: "constructor",
    inputs: [
      { name: "_fxToken", internalType: "address", type: "address" },
      { name: "_uniswapRouter", internalType: "address", type: "address" },
      { name: "_uniswapFactory", internalType: "address", type: "address" },
      { name: "_initialOwner", internalType: "address", type: "address" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [],
    name: "INITIAL_FEE_PERCENTAGE",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "INITIAL_FX_RATE",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "INITIAL_SUPPLY",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "K",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "MAX_FEE_PERCENTAGE",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "MAX_GRADUATION_RESERVE",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "MIN_PURCHASE_AMOUNT",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "_creatorToken", internalType: "address", type: "address" },
      { name: "_amountIn", internalType: "uint256", type: "uint256" },
    ],
    name: "buy",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [{ name: "", internalType: "address", type: "address" }],
    name: "creatorTokenInfo",
    outputs: [
      { name: "user", internalType: "address", type: "address" },
      { name: "graduatedToken", internalType: "address", type: "address" },
      { name: "supply", internalType: "uint256", type: "uint256" },
      { name: "tradingEnabled", internalType: "bool", type: "bool" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    name: "creatorTokens",
    outputs: [{ name: "", internalType: "address", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "feePercentage",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "feeReceiver",
    outputs: [{ name: "", internalType: "address", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "fxRate",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "fxToken",
    outputs: [{ name: "", internalType: "address", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "_creatorToken", internalType: "address", type: "address" },
      { name: "_amountIn", internalType: "uint256", type: "uint256" },
      {
        name: "_orderType",
        internalType: "enum IPumpFun.OrderType",
        type: "uint8",
      },
    ],
    name: "getAmountOut",
    outputs: [{ name: "amountOut", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [{ name: "user", internalType: "address", type: "address" }],
    name: "getCreatorTokens",
    outputs: [{ name: "", internalType: "address[]", type: "address[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "offset", internalType: "uint256", type: "uint256" },
      { name: "limit", internalType: "uint256", type: "uint256" },
    ],
    name: "getCreatorTokensPaginated",
    outputs: [
      { name: "tokens", internalType: "address[]", type: "address[]" },
      { name: "total", internalType: "uint256", type: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "_creatorToken", internalType: "address", type: "address" },
    ],
    name: "getTokenReserves",
    outputs: [
      { name: "", internalType: "uint256", type: "uint256" },
      { name: "", internalType: "uint256", type: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "getTotalCreatorTokens",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "getTotalUsers",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "user", internalType: "address", type: "address" },
      { name: "offset", internalType: "uint256", type: "uint256" },
      { name: "limit", internalType: "uint256", type: "uint256" },
    ],
    name: "getUserCreatorTokensPaginated",
    outputs: [
      { name: "tokens", internalType: "address[]", type: "address[]" },
      { name: "total", internalType: "uint256", type: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "_creatorToken", internalType: "address", type: "address" },
    ],
    name: "graduate",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [],
    name: "initialSupply",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "_creatorToken", internalType: "address", type: "address" },
    ],
    name: "isEligibleForGraduation",
    outputs: [
      { name: "status", internalType: "enum IPumpFun.Status", type: "uint8" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "_purchaseAmount", internalType: "uint256", type: "uint256" },
      { name: "_name", internalType: "string", type: "string" },
      { name: "_symbol", internalType: "string", type: "string" },
    ],
    name: "launch",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "_creatorToken", internalType: "address", type: "address" },
    ],
    name: "migrate",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "_creatorToken", internalType: "address", type: "address" },
      { name: "_user", internalType: "address", type: "address" },
    ],
    name: "migrateFor",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [],
    name: "owner",
    outputs: [{ name: "", internalType: "address", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "pause",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [],
    name: "paused",
    outputs: [{ name: "", internalType: "bool", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [{ name: "", internalType: "address", type: "address" }],
    name: "poolInfo",
    outputs: [
      { name: "creatorReserve", internalType: "uint256", type: "uint256" },
      { name: "fxReserve", internalType: "uint256", type: "uint256" },
      { name: "k", internalType: "uint256", type: "uint256" },
      { name: "feePercentage", internalType: "uint256", type: "uint256" },
      { name: "feeReceiver", internalType: "address", type: "address" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "renounceOwnership",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "_creatorToken", internalType: "address", type: "address" },
      { name: "_amountIn", internalType: "uint256", type: "uint256" },
    ],
    name: "sell",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "_newPercentage", internalType: "uint256", type: "uint256" },
    ],
    name: "setFeePercentage",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "_newReceiver", internalType: "address", type: "address" },
    ],
    name: "setFeeReceiver",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [{ name: "_newRate", internalType: "uint256", type: "uint256" }],
    name: "setFxRate",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [{ name: "_newSupply", internalType: "uint256", type: "uint256" }],
    name: "setInitialSupply",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [{ name: "newOwner", internalType: "address", type: "address" }],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [],
    name: "uniswapFactory",
    outputs: [
      { name: "", internalType: "contract IUniswapV2Factory", type: "address" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "uniswapRouter",
    outputs: [
      {
        name: "",
        internalType: "contract IUniswapV2Router02",
        type: "address",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "unpause",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    name: "users",
    outputs: [{ name: "", internalType: "address", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      { name: "user", internalType: "address", type: "address", indexed: true },
      {
        name: "creatorToken",
        internalType: "address",
        type: "address",
        indexed: true,
      },
    ],
    name: "CreatorTokenAdded",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "creatorToken",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "feeReceiver",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "feeAmount",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "FeeCollected",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "feePercentage",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "FeePercentageUpdated",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "feeReceiver",
        internalType: "address",
        type: "address",
        indexed: true,
      },
    ],
    name: "FeeReceiverUpdated",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "fxRate",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "FxRateUpdated",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "creatorToken",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "graduatedToken",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "creatorLiquidity",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
      {
        name: "fxLiquidity",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "Graduated",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "creatorToken",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      { name: "user", internalType: "address", type: "address", indexed: true },
      {
        name: "creatorTokenRefund",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
      {
        name: "fxTokenRefund",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "GraduationRefund",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "initialSupply",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "InitialSupplyUpdated",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "creatorToken",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      { name: "id", internalType: "uint256", type: "uint256", indexed: true },
      { name: "name", internalType: "string", type: "string", indexed: false },
      {
        name: "symbol",
        internalType: "string",
        type: "string",
        indexed: false,
      },
      {
        name: "purchaseAmount",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
      {
        name: "liquidityAmount",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "Launched",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      { name: "user", internalType: "address", type: "address", indexed: true },
      {
        name: "creatorToken",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "graduatedToken",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "amount",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "Migrated",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "previousOwner",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "newOwner",
        internalType: "address",
        type: "address",
        indexed: true,
      },
    ],
    name: "OwnershipTransferred",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "account",
        internalType: "address",
        type: "address",
        indexed: false,
      },
    ],
    name: "Paused",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "creatorToken",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "feeReceiver",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "creatorReserve",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
      {
        name: "fxReserve",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
      { name: "k", internalType: "uint256", type: "uint256", indexed: false },
      {
        name: "feeAmount",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "PoolInitialized",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "creatorToken",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "creatorReserve",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
      {
        name: "fxReserve",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "PoolUpdated",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "creatorToken",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "amountIn",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
      {
        name: "amountOut",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "Purchased",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "creatorToken",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "amountIn",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
      {
        name: "amountOut",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "Sold",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "account",
        internalType: "address",
        type: "address",
        indexed: false,
      },
    ],
    name: "Unpaused",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      { name: "user", internalType: "address", type: "address", indexed: true },
    ],
    name: "UserCreated",
  },
  { type: "error", inputs: [], name: "EnforcedPause" },
  { type: "error", inputs: [], name: "ExpectedPause" },
  {
    type: "error",
    inputs: [{ name: "owner", internalType: "address", type: "address" }],
    name: "OwnableInvalidOwner",
  },
  {
    type: "error",
    inputs: [{ name: "account", internalType: "address", type: "address" }],
    name: "OwnableUnauthorizedAccount",
  },
  { type: "error", inputs: [], name: "PumpFun__FeeExceedsMaximum" },
  { type: "error", inputs: [], name: "PumpFun__InsufficientLiquidity" },
  { type: "error", inputs: [], name: "PumpFun__InvalidGraduationReserve" },
  { type: "error", inputs: [], name: "PumpFun__InvalidPurchaseAmount" },
  { type: "error", inputs: [], name: "PumpFun__InvalidRate" },
  { type: "error", inputs: [], name: "PumpFun__InvalidSupply" },
  { type: "error", inputs: [], name: "PumpFun__NoTokensToMigrate" },
  { type: "error", inputs: [], name: "PumpFun__NotTokenCreator" },
  { type: "error", inputs: [], name: "PumpFun__TokenNotGraduated" },
  { type: "error", inputs: [], name: "PumpFun__TokenNotLaunched" },
  { type: "error", inputs: [], name: "PumpFun__TradingNotEnabled" },
  { type: "error", inputs: [], name: "PumpFun__ZeroAddress" },
  { type: "error", inputs: [], name: "PumpFun__ZeroAmountIn" },
  {
    type: "error",
    inputs: [{ name: "token", internalType: "address", type: "address" }],
    name: "SafeERC20FailedOperation",
  },
] as const

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// TezAirdrop
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const tezAirdropAbi = [
  {
    type: "constructor",
    inputs: [
      { name: "_owner", internalType: "address", type: "address" },
      { name: "_fxToken", internalType: "address", type: "address" },
      { name: "_signer", internalType: "address", type: "address" },
      { name: "_merkleRoot", internalType: "bytes32", type: "bytes32" },
      { name: "_lockTime", internalType: "uint256", type: "uint256" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [],
    name: "TEZ_WALLET_TYPEHASH",
    outputs: [{ name: "", internalType: "bytes32", type: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "_amount", internalType: "uint256", type: "uint256" },
      { name: "_wallet", internalType: "string", type: "string" },
      { name: "_signature", internalType: "bytes", type: "bytes" },
      { name: "_merkleProof", internalType: "bytes32[]", type: "bytes32[]" },
    ],
    name: "claim",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "_user", internalType: "address", type: "address" },
      { name: "_amount", internalType: "uint256", type: "uint256" },
      { name: "_wallet", internalType: "string", type: "string" },
      { name: "_signature", internalType: "bytes", type: "bytes" },
      { name: "_merkleProof", internalType: "bytes32[]", type: "bytes32[]" },
    ],
    name: "claimFor",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "_to", internalType: "address", type: "address" },
      { name: "_amount", internalType: "uint256", type: "uint256" },
      { name: "_wallet", internalType: "string", type: "string" },
      { name: "_signature", internalType: "bytes", type: "bytes" },
      { name: "_merkleProof", internalType: "bytes32[]", type: "bytes32[]" },
    ],
    name: "claimTo",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [],
    name: "eip712Domain",
    outputs: [
      { name: "fields", internalType: "bytes1", type: "bytes1" },
      { name: "name", internalType: "string", type: "string" },
      { name: "version", internalType: "string", type: "string" },
      { name: "chainId", internalType: "uint256", type: "uint256" },
      { name: "verifyingContract", internalType: "address", type: "address" },
      { name: "salt", internalType: "bytes32", type: "bytes32" },
      { name: "extensions", internalType: "uint256[]", type: "uint256[]" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "fxToken",
    outputs: [{ name: "", internalType: "address", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "_caller", internalType: "address", type: "address" },
      { name: "_wallet", internalType: "string", type: "string" },
    ],
    name: "generateTezWalletHash",
    outputs: [{ name: "", internalType: "bytes32", type: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [{ name: "", internalType: "string", type: "string" }],
    name: "hasClaimed",
    outputs: [{ name: "", internalType: "bool", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "lockTimestamp",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "merkleRoot",
    outputs: [{ name: "", internalType: "bytes32", type: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "owner",
    outputs: [{ name: "", internalType: "address", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "renounceOwnership",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [],
    name: "signer",
    outputs: [{ name: "", internalType: "address", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [{ name: "newOwner", internalType: "address", type: "address" }],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "_newTimestamp", internalType: "uint256", type: "uint256" },
    ],
    name: "updateLockTimestamp",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [{ name: "_newRoot", internalType: "bytes32", type: "bytes32" }],
    name: "updateMerkleRoot",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [{ name: "_newSigner", internalType: "address", type: "address" }],
    name: "updateSigner",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [{ name: "_to", internalType: "address", type: "address" }],
    name: "withdraw",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      { name: "user", internalType: "address", type: "address", indexed: true },
      { name: "wallet", internalType: "string", type: "string", indexed: true },
      {
        name: "amount",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "AirdropClaimed",
  },
  { type: "event", anonymous: false, inputs: [], name: "EIP712DomainChanged" },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "newTimestamp",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "LockTimestampUpdated",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "newRoot",
        internalType: "bytes32",
        type: "bytes32",
        indexed: false,
      },
    ],
    name: "MerkleRootUpdated",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "previousOwner",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "newOwner",
        internalType: "address",
        type: "address",
        indexed: true,
      },
    ],
    name: "OwnershipTransferred",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "newSigner",
        internalType: "address",
        type: "address",
        indexed: false,
      },
    ],
    name: "SignerUpdated",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      { name: "to", internalType: "address", type: "address", indexed: false },
      {
        name: "amount",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "Withdrawal",
  },
  { type: "error", inputs: [], name: "ECDSAInvalidSignature" },
  {
    type: "error",
    inputs: [{ name: "length", internalType: "uint256", type: "uint256" }],
    name: "ECDSAInvalidSignatureLength",
  },
  {
    type: "error",
    inputs: [{ name: "s", internalType: "bytes32", type: "bytes32" }],
    name: "ECDSAInvalidSignatureS",
  },
  { type: "error", inputs: [], name: "InvalidShortString" },
  {
    type: "error",
    inputs: [{ name: "owner", internalType: "address", type: "address" }],
    name: "OwnableInvalidOwner",
  },
  {
    type: "error",
    inputs: [{ name: "account", internalType: "address", type: "address" }],
    name: "OwnableUnauthorizedAccount",
  },
  {
    type: "error",
    inputs: [{ name: "token", internalType: "address", type: "address" }],
    name: "SafeERC20FailedOperation",
  },
  {
    type: "error",
    inputs: [{ name: "str", internalType: "string", type: "string" }],
    name: "StringTooLong",
  },
  { type: "error", inputs: [], name: "TezAirdrop__AlreadyClaimed" },
  { type: "error", inputs: [], name: "TezAirdrop__InvalidProof" },
  { type: "error", inputs: [], name: "TezAirdrop__InvalidSignature" },
  { type: "error", inputs: [], name: "TezAirdrop__LockTimeElapsed" },
  { type: "error", inputs: [], name: "TezAirdrop__LockTimeNotElapsed" },
  { type: "error", inputs: [], name: "TezAirdrop__ZeroAmount" },
] as const
