//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// DutchAuctionV2
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const dutchAuctionV2Abi = [
  {
    type: "constructor",
    inputs: [
      { name: "_owner", internalType: "address", type: "address" },
      { name: "_feeManager", internalType: "address", type: "address" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "", internalType: "address", type: "address" },
      { name: "", internalType: "uint256", type: "uint256" },
    ],
    name: "auctions",
    outputs: [
      { name: "refunded", internalType: "bool", type: "bool" },
      { name: "stepLength", internalType: "uint248", type: "uint248" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "_token", internalType: "address", type: "address" },
      { name: "_reserveId", internalType: "uint256", type: "uint256" },
      { name: "_amount", internalType: "uint256", type: "uint256" },
      { name: "_to", internalType: "address", type: "address" },
    ],
    name: "buy",
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    inputs: [
      { name: "_token", internalType: "address", type: "address" },
      { name: "_reserveId", internalType: "uint256", type: "uint256" },
      { name: "_to", internalType: "address", type: "address" },
      { name: "_indexes", internalType: "uint256[]", type: "uint256[]" },
      { name: "_proofs", internalType: "bytes32[][]", type: "bytes32[][]" },
    ],
    name: "buyAllowlist",
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    inputs: [
      { name: "_token", internalType: "address", type: "address" },
      { name: "_reserveId", internalType: "uint256", type: "uint256" },
      { name: "_amount", internalType: "uint256", type: "uint256" },
      { name: "_to", internalType: "address", type: "address" },
      { name: "_index", internalType: "uint256", type: "uint256" },
      { name: "_signature", internalType: "bytes", type: "bytes" },
    ],
    name: "buyMintPass",
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    inputs: [],
    name: "cancelOwnershipHandover",
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    inputs: [
      { name: "pendingOwner", internalType: "address", type: "address" },
    ],
    name: "completeOwnershipHandover",
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    inputs: [],
    name: "eip712Domain",
    outputs: [
      { name: "fields", internalType: "bytes1", type: "bytes1" },
      { name: "name", internalType: "string", type: "string" },
      { name: "version", internalType: "string", type: "string" },
      { name: "chainId", internalType: "uint256", type: "uint256" },
      { name: "verifyingContract", internalType: "address", type: "address" },
      { name: "salt", internalType: "bytes32", type: "bytes32" },
      { name: "extensions", internalType: "uint256[]", type: "uint256[]" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "feeManager",
    outputs: [{ name: "", internalType: "address", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "_token", internalType: "address", type: "address" },
      { name: "_reserveId", internalType: "uint256", type: "uint256" },
      { name: "_reserveNonce", internalType: "uint256", type: "uint256" },
      { name: "_index", internalType: "uint256", type: "uint256" },
      { name: "_claimer", internalType: "address", type: "address" },
    ],
    name: "generateTypedDataHash",
    outputs: [{ name: "", internalType: "bytes32", type: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [{ name: "_token", internalType: "address", type: "address" }],
    name: "getFirstValidReserve",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [{ name: "_token", internalType: "address", type: "address" }],
    name: "getLatestUpdate",
    outputs: [{ name: "", internalType: "uint40", type: "uint40" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "_token", internalType: "address", type: "address" },
      { name: "_reserveId", internalType: "uint256", type: "uint256" },
    ],
    name: "getPrice",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "", internalType: "address", type: "address" },
      { name: "", internalType: "uint256", type: "uint256" },
    ],
    name: "merkleRoots",
    outputs: [{ name: "", internalType: "bytes32", type: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "", internalType: "address", type: "address" },
      { name: "", internalType: "uint256", type: "uint256" },
    ],
    name: "numberMinted",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "owner",
    outputs: [{ name: "result", internalType: "address", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "pendingOwner", internalType: "address", type: "address" },
    ],
    name: "ownershipHandoverExpiresAt",
    outputs: [{ name: "result", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "pause",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [],
    name: "paused",
    outputs: [{ name: "", internalType: "bool", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "_token", internalType: "address", type: "address" },
      { name: "_reserveId", internalType: "uint256", type: "uint256" },
      { name: "_buyer", internalType: "address", type: "address" },
    ],
    name: "refund",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "", internalType: "address", type: "address" },
      { name: "", internalType: "uint256", type: "uint256" },
    ],
    name: "refunds",
    outputs: [{ name: "lastPrice", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "renounceOwnership",
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    inputs: [],
    name: "requestOwnershipHandover",
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    inputs: [
      { name: "", internalType: "address", type: "address" },
      { name: "", internalType: "uint256", type: "uint256" },
    ],
    name: "reserveNonce",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "", internalType: "address", type: "address" },
      { name: "", internalType: "uint256", type: "uint256" },
    ],
    name: "reserves",
    outputs: [
      { name: "startTime", internalType: "uint64", type: "uint64" },
      { name: "endTime", internalType: "uint64", type: "uint64" },
      { name: "allocation", internalType: "uint128", type: "uint128" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "", internalType: "address", type: "address" },
      { name: "", internalType: "uint256", type: "uint256" },
    ],
    name: "saleProceeds",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [{ name: "_feeManager", internalType: "address", type: "address" }],
    name: "setFeeManager",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      {
        name: "_reserve",
        internalType: "struct ReserveInfo",
        type: "tuple",
        components: [
          { name: "startTime", internalType: "uint64", type: "uint64" },
          { name: "endTime", internalType: "uint64", type: "uint64" },
          { name: "allocation", internalType: "uint128", type: "uint128" },
        ],
      },
      { name: "_mintDetails", internalType: "bytes", type: "bytes" },
    ],
    name: "setMintDetails",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "", internalType: "address", type: "address" },
      { name: "", internalType: "uint256", type: "uint256" },
    ],
    name: "signingAuthorities",
    outputs: [{ name: "", internalType: "address", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [{ name: "newOwner", internalType: "address", type: "address" }],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    inputs: [],
    name: "unpause",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "_token", internalType: "address", type: "address" },
      { name: "_reserveId", internalType: "uint256", type: "uint256" },
    ],
    name: "withdraw",
    outputs: [],
    stateMutability: "nonpayable",
  },
  { type: "event", anonymous: false, inputs: [], name: "EIP712DomainChanged" },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "_prevManager",
        internalType: "address",
        type: "address",
        indexed: false,
      },
      {
        name: "_newManager",
        internalType: "address",
        type: "address",
        indexed: false,
      },
    ],
    name: "FeeManagerSet",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "_token",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "_reserveId",
        internalType: "uint256",
        type: "uint256",
        indexed: true,
      },
      {
        name: "_reserveInfo",
        internalType: "struct ReserveInfo",
        type: "tuple",
        components: [
          { name: "startTime", internalType: "uint64", type: "uint64" },
          { name: "endTime", internalType: "uint64", type: "uint64" },
          { name: "allocation", internalType: "uint128", type: "uint128" },
        ],
        indexed: false,
      },
      {
        name: "_merkleRoot",
        internalType: "bytes32",
        type: "bytes32",
        indexed: false,
      },
      {
        name: "_mintPassSigner",
        internalType: "address",
        type: "address",
        indexed: false,
      },
      {
        name: "_auctionInfo",
        internalType: "struct AuctionInfo",
        type: "tuple",
        components: [
          { name: "refunded", internalType: "bool", type: "bool" },
          { name: "stepLength", internalType: "uint248", type: "uint248" },
          { name: "prices", internalType: "uint256[]", type: "uint256[]" },
        ],
        indexed: false,
      },
    ],
    name: "MintDetailsSet",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "pendingOwner",
        internalType: "address",
        type: "address",
        indexed: true,
      },
    ],
    name: "OwnershipHandoverCanceled",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "pendingOwner",
        internalType: "address",
        type: "address",
        indexed: true,
      },
    ],
    name: "OwnershipHandoverRequested",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "oldOwner",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "newOwner",
        internalType: "address",
        type: "address",
        indexed: true,
      },
    ],
    name: "OwnershipTransferred",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "_token",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "_reserveId",
        internalType: "uint256",
        type: "uint256",
        indexed: true,
      },
      {
        name: "_claimer",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "_index",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "PassClaimed",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "account",
        internalType: "address",
        type: "address",
        indexed: false,
      },
    ],
    name: "Paused",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "_token",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "_reserveId",
        internalType: "uint256",
        type: "uint256",
        indexed: true,
      },
      {
        name: "_buyer",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      { name: "_to", internalType: "address", type: "address", indexed: false },
      {
        name: "_amount",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
      {
        name: "_price",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
      {
        name: "_platformFee",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
      {
        name: "_mintFee",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
      {
        name: "_splitAmount",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "Purchase",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "_token",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "_reserveId",
        internalType: "uint256",
        type: "uint256",
        indexed: true,
      },
      {
        name: "_buyer",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "_refundAmount",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "RefundClaimed",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "_token",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "_reserveId",
        internalType: "uint256",
        type: "uint256",
        indexed: true,
      },
      {
        name: "_claimer",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "_index",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "SlotClaimed",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "account",
        internalType: "address",
        type: "address",
        indexed: false,
      },
    ],
    name: "Unpaused",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "_token",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "_reserveId",
        internalType: "uint256",
        type: "uint256",
        indexed: true,
      },
      {
        name: "_creator",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "_proceeds",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "Withdrawn",
  },
  { type: "error", inputs: [], name: "AddressZero" },
  { type: "error", inputs: [], name: "InsufficientFunds" },
  { type: "error", inputs: [], name: "InsufficientPrice" },
  { type: "error", inputs: [], name: "InvalidAllocation" },
  { type: "error", inputs: [], name: "InvalidAmount" },
  { type: "error", inputs: [], name: "InvalidPayment" },
  { type: "error", inputs: [], name: "InvalidPrice" },
  { type: "error", inputs: [], name: "InvalidPriceCurve" },
  { type: "error", inputs: [], name: "InvalidProof" },
  { type: "error", inputs: [], name: "InvalidReserve" },
  { type: "error", inputs: [], name: "InvalidShortString" },
  { type: "error", inputs: [], name: "InvalidSignature" },
  { type: "error", inputs: [], name: "InvalidStep" },
  { type: "error", inputs: [], name: "InvalidToken" },
  { type: "error", inputs: [], name: "NewOwnerIsZeroAddress" },
  { type: "error", inputs: [], name: "NoAllowlist" },
  { type: "error", inputs: [], name: "NoHandoverRequest" },
  { type: "error", inputs: [], name: "NoPublicMint" },
  { type: "error", inputs: [], name: "NoRefund" },
  { type: "error", inputs: [], name: "NoSigningAuthority" },
  { type: "error", inputs: [], name: "NonRefundableDA" },
  { type: "error", inputs: [], name: "NotEnded" },
  { type: "error", inputs: [], name: "NotStarted" },
  { type: "error", inputs: [], name: "OnlyAuthorityOrAllowlist" },
  { type: "error", inputs: [], name: "PassAlreadyClaimed" },
  { type: "error", inputs: [], name: "PricesOutOfOrder" },
  { type: "error", inputs: [], name: "SlotAlreadyClaimed" },
  {
    type: "error",
    inputs: [{ name: "str", internalType: "string", type: "string" }],
    name: "StringTooLong",
  },
  { type: "error", inputs: [], name: "Unauthorized" },
] as const

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// FxAirdrop
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const fxAirdropAbi = [
  {
    type: "constructor",
    inputs: [
      { name: "_owner", internalType: "address", type: "address" },
      { name: "_fxToken", internalType: "address", type: "address" },
      { name: "_merkleRoot", internalType: "bytes32", type: "bytes32" },
      { name: "_lockTime", internalType: "uint256", type: "uint256" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "_amount", internalType: "uint256", type: "uint256" },
      { name: "_merkleProof", internalType: "bytes32[]", type: "bytes32[]" },
    ],
    name: "claim",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "_user", internalType: "address", type: "address" },
      { name: "_amount", internalType: "uint256", type: "uint256" },
      { name: "_merkleProof", internalType: "bytes32[]", type: "bytes32[]" },
    ],
    name: "claimFor",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "_to", internalType: "address", type: "address" },
      { name: "_amount", internalType: "uint256", type: "uint256" },
      { name: "_merkleProof", internalType: "bytes32[]", type: "bytes32[]" },
    ],
    name: "claimTo",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [],
    name: "fxToken",
    outputs: [{ name: "", internalType: "address", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [{ name: "", internalType: "address", type: "address" }],
    name: "hasClaimed",
    outputs: [{ name: "", internalType: "bool", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "lockTimestamp",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "merkleRoot",
    outputs: [{ name: "", internalType: "bytes32", type: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "owner",
    outputs: [{ name: "", internalType: "address", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "renounceOwnership",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [{ name: "newOwner", internalType: "address", type: "address" }],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "_newTimestamp", internalType: "uint256", type: "uint256" },
    ],
    name: "updateLockTimestamp",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [{ name: "_newRoot", internalType: "bytes32", type: "bytes32" }],
    name: "updateMerkleRoot",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [{ name: "_to", internalType: "address", type: "address" }],
    name: "withdraw",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      { name: "user", internalType: "address", type: "address", indexed: true },
      {
        name: "amount",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "AirdropClaimed",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "newTimestamp",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "LockTimestampUpdated",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "newRoot",
        internalType: "bytes32",
        type: "bytes32",
        indexed: false,
      },
    ],
    name: "MerkleRootUpdated",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "previousOwner",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "newOwner",
        internalType: "address",
        type: "address",
        indexed: true,
      },
    ],
    name: "OwnershipTransferred",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      { name: "to", internalType: "address", type: "address", indexed: false },
      {
        name: "amount",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "Withdrawal",
  },
  { type: "error", inputs: [], name: "FxAirdrop__AlreadyClaimed" },
  { type: "error", inputs: [], name: "FxAirdrop__InvalidProof" },
  { type: "error", inputs: [], name: "FxAirdrop__LockTimeElapsed" },
  { type: "error", inputs: [], name: "FxAirdrop__LockTimeNotElapsed" },
  { type: "error", inputs: [], name: "FxAirdrop__ZeroAmount" },
  {
    type: "error",
    inputs: [{ name: "owner", internalType: "address", type: "address" }],
    name: "OwnableInvalidOwner",
  },
  {
    type: "error",
    inputs: [{ name: "account", internalType: "address", type: "address" }],
    name: "OwnableUnauthorizedAccount",
  },
  {
    type: "error",
    inputs: [{ name: "token", internalType: "address", type: "address" }],
    name: "SafeERC20FailedOperation",
  },
] as const

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// ProjectFactory
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const projectFactoryAbi = [
  {
    type: "constructor",
    inputs: [
      { name: "_initialOwner", internalType: "address", type: "address" },
      { name: "_initialAdmin", internalType: "address", type: "address" },
      { name: "_initialRenderer", internalType: "address", type: "address" },
      { name: "_tokenLaunchpad", internalType: "address", type: "address" },
      { name: "_fxToken", internalType: "address", type: "address" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "_name", internalType: "string", type: "string" },
      { name: "_symbol", internalType: "string", type: "string" },
      { name: "_creatorToken", internalType: "address", type: "address" },
      { name: "_initialOwner", internalType: "address", type: "address" },
      { name: "_baseURI", internalType: "string", type: "string" },
      {
        name: "_mintInfo",
        internalType: "struct IProjectToken.MintInfo",
        type: "tuple",
        components: [
          { name: "price", internalType: "uint256", type: "uint256" },
          { name: "maxSupply", internalType: "uint256", type: "uint256" },
        ],
      },
      { name: "_tagIds", internalType: "uint256[]", type: "uint256[]" },
    ],
    name: "createProject",
    outputs: [
      { name: "projectToken", internalType: "address", type: "address" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "_name", internalType: "string", type: "string" },
      { name: "_symbol", internalType: "string", type: "string" },
      { name: "_initialOwner", internalType: "address", type: "address" },
      { name: "_baseURI", internalType: "string", type: "string" },
      {
        name: "_mintInfo",
        internalType: "struct IProjectToken.MintInfo",
        type: "tuple",
        components: [
          { name: "price", internalType: "uint256", type: "uint256" },
          { name: "maxSupply", internalType: "uint256", type: "uint256" },
        ],
      },
      { name: "_tagIds", internalType: "uint256[]", type: "uint256[]" },
      { name: "_fxAmount", internalType: "uint256", type: "uint256" },
    ],
    name: "createProjectAndLaunchToken",
    outputs: [
      { name: "projectToken", internalType: "address", type: "address" },
      { name: "creatorToken", internalType: "address", type: "address" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [],
    name: "initialAdmin",
    outputs: [{ name: "", internalType: "address", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "initialRenderer",
    outputs: [{ name: "", internalType: "address", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "owner",
    outputs: [{ name: "", internalType: "address", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "pause",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [],
    name: "paused",
    outputs: [{ name: "", internalType: "bool", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "projectId",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    name: "projects",
    outputs: [{ name: "", internalType: "address", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "renounceOwnership",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "_initialAdmin", internalType: "address", type: "address" },
    ],
    name: "setInitialAdmin",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "_initialRenderer", internalType: "address", type: "address" },
    ],
    name: "setInitialRenderer",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "_tokenLaunchpad", internalType: "address", type: "address" },
    ],
    name: "setTokenLaunchpad",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [],
    name: "tokenLaunchpad",
    outputs: [{ name: "", internalType: "address", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [{ name: "newOwner", internalType: "address", type: "address" }],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [],
    name: "unpause",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "oldAdmin",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "newAdmin",
        internalType: "address",
        type: "address",
        indexed: true,
      },
    ],
    name: "InitialAdminUpdated",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "oldRenderer",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "newRenderer",
        internalType: "address",
        type: "address",
        indexed: true,
      },
    ],
    name: "InitialRendererUpdated",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "previousOwner",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "newOwner",
        internalType: "address",
        type: "address",
        indexed: true,
      },
    ],
    name: "OwnershipTransferred",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "account",
        internalType: "address",
        type: "address",
        indexed: false,
      },
    ],
    name: "Paused",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "projectId",
        internalType: "uint256",
        type: "uint256",
        indexed: true,
      },
      {
        name: "projectToken",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "creatorToken",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "creator",
        internalType: "address",
        type: "address",
        indexed: false,
      },
      { name: "name", internalType: "string", type: "string", indexed: false },
    ],
    name: "ProjectCreated",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "oldTokenLaunchpad",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "newTokenLaunchpad",
        internalType: "address",
        type: "address",
        indexed: true,
      },
    ],
    name: "TokenLaunchpadUpdated",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "account",
        internalType: "address",
        type: "address",
        indexed: false,
      },
    ],
    name: "Unpaused",
  },
  { type: "error", inputs: [], name: "EnforcedPause" },
  { type: "error", inputs: [], name: "ExpectedPause" },
  {
    type: "error",
    inputs: [{ name: "owner", internalType: "address", type: "address" }],
    name: "OwnableInvalidOwner",
  },
  {
    type: "error",
    inputs: [{ name: "account", internalType: "address", type: "address" }],
    name: "OwnableUnauthorizedAccount",
  },
  { type: "error", inputs: [], name: "ProjectFactory__NotCreator" },
  { type: "error", inputs: [], name: "ProjectFactory__TokenLaunchpadNotSet" },
  { type: "error", inputs: [], name: "ProjectFactory__ZeroAddress" },
  {
    type: "error",
    inputs: [{ name: "token", internalType: "address", type: "address" }],
    name: "SafeERC20FailedOperation",
  },
] as const

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// ProjectToken
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const projectTokenAbi = [
  {
    type: "constructor",
    inputs: [
      { name: "_initialAdmin", internalType: "address", type: "address" },
      { name: "_initialBaseURI", internalType: "string", type: "string" },
      { name: "_initialRenderer", internalType: "address", type: "address" },
      { name: "_name", internalType: "string", type: "string" },
      { name: "_symbol", internalType: "string", type: "string" },
      { name: "_creatorToken", internalType: "address", type: "address" },
      { name: "_initialOwner", internalType: "address", type: "address" },
      {
        name: "_mintInfo",
        internalType: "struct IProjectToken.MintInfo",
        type: "tuple",
        components: [
          { name: "price", internalType: "uint256", type: "uint256" },
          { name: "maxSupply", internalType: "uint256", type: "uint256" },
        ],
      },
      { name: "_tagIds", internalType: "uint256[]", type: "uint256[]" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [{ name: "_currency", internalType: "address", type: "address" }],
    name: "addSupportedCurrency",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [],
    name: "admin",
    outputs: [{ name: "", internalType: "address", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "to", internalType: "address", type: "address" },
      { name: "tokenId", internalType: "uint256", type: "uint256" },
    ],
    name: "approve",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [{ name: "owner", internalType: "address", type: "address" }],
    name: "balanceOf",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "baseURI",
    outputs: [{ name: "", internalType: "string", type: "string" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [{ name: "tokenId", internalType: "uint256", type: "uint256" }],
    name: "burn",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [],
    name: "contractURI",
    outputs: [{ name: "", internalType: "string", type: "string" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "creatorFeeNumerator",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "creatorFeeReceiver",
    outputs: [{ name: "", internalType: "address", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "creatorToken",
    outputs: [{ name: "", internalType: "address", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "currentFeeCurrency",
    outputs: [{ name: "", internalType: "address", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "currentTokenId",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "fxFeeNumerator",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "fxFeeReceiver",
    outputs: [{ name: "", internalType: "address", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [{ name: "tokenId", internalType: "uint256", type: "uint256" }],
    name: "getApproved",
    outputs: [{ name: "", internalType: "address", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "owner", internalType: "address", type: "address" },
      { name: "operator", internalType: "address", type: "address" },
    ],
    name: "isApprovedForAll",
    outputs: [{ name: "", internalType: "bool", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [{ name: "_tokenId", internalType: "uint256", type: "uint256" }],
    name: "isMetadataLocked",
    outputs: [{ name: "", internalType: "bool", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [{ name: "_tokenId", internalType: "uint256", type: "uint256" }],
    name: "lockMetadata",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [{ name: "_to", internalType: "address", type: "address" }],
    name: "mint",
    outputs: [
      { name: "nextTokenId", internalType: "uint256", type: "uint256" },
    ],
    stateMutability: "payable",
  },
  {
    type: "function",
    inputs: [{ name: "", internalType: "address", type: "address" }],
    name: "mintFee",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "mintInfo",
    outputs: [
      { name: "price", internalType: "uint256", type: "uint256" },
      { name: "maxSupply", internalType: "uint256", type: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "name",
    outputs: [{ name: "", internalType: "string", type: "string" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "owner",
    outputs: [{ name: "", internalType: "address", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [{ name: "tokenId", internalType: "uint256", type: "uint256" }],
    name: "ownerOf",
    outputs: [{ name: "", internalType: "address", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "pause",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [],
    name: "paused",
    outputs: [{ name: "", internalType: "bool", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [{ name: "_tokenId", internalType: "uint256", type: "uint256" }],
    name: "redeem",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [{ name: "_currency", internalType: "address", type: "address" }],
    name: "removeSupportedCurrency",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [],
    name: "renderer",
    outputs: [{ name: "", internalType: "address", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "renounceAdmin",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [],
    name: "renounceOwnership",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "_tokenId", internalType: "uint256", type: "uint256" },
      { name: "_to", internalType: "address", type: "address" },
    ],
    name: "reroll",
    outputs: [{ name: "newTokenId", internalType: "uint256", type: "uint256" }],
    stateMutability: "payable",
  },
  {
    type: "function",
    inputs: [
      { name: "from", internalType: "address", type: "address" },
      { name: "to", internalType: "address", type: "address" },
      { name: "tokenId", internalType: "uint256", type: "uint256" },
    ],
    name: "safeTransferFrom",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "from", internalType: "address", type: "address" },
      { name: "to", internalType: "address", type: "address" },
      { name: "tokenId", internalType: "uint256", type: "uint256" },
      { name: "data", internalType: "bytes", type: "bytes" },
    ],
    name: "safeTransferFrom",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "operator", internalType: "address", type: "address" },
      { name: "approved", internalType: "bool", type: "bool" },
    ],
    name: "setApprovalForAll",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [{ name: "_newURI", internalType: "string", type: "string" }],
    name: "setBaseURI",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "_newReceiver", internalType: "address", type: "address" },
    ],
    name: "setCreatorFeeReceiver",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [{ name: "_currency", internalType: "address", type: "address" }],
    name: "setCurrentFeeCurrency",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "_fxNumerator", internalType: "uint256", type: "uint256" },
      { name: "_creatorNumerator", internalType: "uint256", type: "uint256" },
    ],
    name: "setFeeSplit",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "_newReceiver", internalType: "address", type: "address" },
    ],
    name: "setFxFeeReceiver",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "_currency", internalType: "address", type: "address" },
      { name: "_fee", internalType: "uint256", type: "uint256" },
    ],
    name: "setMintFee",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [{ name: "_newPrice", internalType: "uint256", type: "uint256" }],
    name: "setMintPrice",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "_newRenderer", internalType: "address", type: "address" },
    ],
    name: "setRenderer",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [{ name: "_tagIds", internalType: "uint256[]", type: "uint256[]" }],
    name: "setTags",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [{ name: "", internalType: "address", type: "address" }],
    name: "supportedCurrencies",
    outputs: [{ name: "", internalType: "bool", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [{ name: "_interfaceId", internalType: "bytes4", type: "bytes4" }],
    name: "supportsInterface",
    outputs: [{ name: "", internalType: "bool", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "symbol",
    outputs: [{ name: "", internalType: "string", type: "string" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [{ name: "index", internalType: "uint256", type: "uint256" }],
    name: "tokenByIndex",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    name: "tokenInfo",
    outputs: [
      { name: "minter", internalType: "address", type: "address" },
      { name: "mintPrice", internalType: "uint256", type: "uint256" },
      { name: "seed", internalType: "bytes32", type: "bytes32" },
      { name: "lockedTokenURI", internalType: "string", type: "string" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "owner", internalType: "address", type: "address" },
      { name: "index", internalType: "uint256", type: "uint256" },
    ],
    name: "tokenOfOwnerByIndex",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [{ name: "_tokenId", internalType: "uint256", type: "uint256" }],
    name: "tokenURI",
    outputs: [{ name: "", internalType: "string", type: "string" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "totalSupply",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [{ name: "_newAdmin", internalType: "address", type: "address" }],
    name: "transferAdmin",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "from", internalType: "address", type: "address" },
      { name: "to", internalType: "address", type: "address" },
      { name: "tokenId", internalType: "uint256", type: "uint256" },
    ],
    name: "transferFrom",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [{ name: "newOwner", internalType: "address", type: "address" }],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [],
    name: "unpause",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "owner",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "approved",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "tokenId",
        internalType: "uint256",
        type: "uint256",
        indexed: true,
      },
    ],
    name: "Approval",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "owner",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "operator",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      { name: "approved", internalType: "bool", type: "bool", indexed: false },
    ],
    name: "ApprovalForAll",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "currentURI",
        internalType: "string",
        type: "string",
        indexed: false,
      },
      {
        name: "newURI",
        internalType: "string",
        type: "string",
        indexed: false,
      },
    ],
    name: "BaseURIUpdated",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "previousCurrency",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "newCurrency",
        internalType: "address",
        type: "address",
        indexed: true,
      },
    ],
    name: "CurrentFeeCurrencyUpdated",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "currency",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "fxAmount",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
      {
        name: "creatorAmount",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "FeeDistributed",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "creatorFeeReceiver",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "fxFeeReceiver",
        internalType: "address",
        type: "address",
        indexed: true,
      },
    ],
    name: "FeeReceiversUpdated",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "fxNumerator",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
      {
        name: "creatorNumerator",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "FeeSplitUpdated",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "tokenId",
        internalType: "uint256",
        type: "uint256",
        indexed: true,
      },
      {
        name: "owner",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      { name: "uri", internalType: "string", type: "string", indexed: false },
    ],
    name: "MetadataLocked",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "tokenId",
        internalType: "uint256",
        type: "uint256",
        indexed: true,
      },
      {
        name: "owner",
        internalType: "address",
        type: "address",
        indexed: true,
      },
    ],
    name: "MetadataUnlocked",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "currency",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      { name: "fee", internalType: "uint256", type: "uint256", indexed: false },
    ],
    name: "MintFeeUpdated",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "price",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
      {
        name: "maxSupply",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "MintInfoInitialized",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "currentPrice",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
      {
        name: "newPrice",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "MintPriceUpdated",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "previousOwner",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "newOwner",
        internalType: "address",
        type: "address",
        indexed: true,
      },
    ],
    name: "OwnershipTransferred",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "account",
        internalType: "address",
        type: "address",
        indexed: false,
      },
    ],
    name: "Paused",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "tagIds",
        internalType: "uint256[]",
        type: "uint256[]",
        indexed: false,
      },
    ],
    name: "ProjectTags",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "currentRenderer",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "newRenderer",
        internalType: "address",
        type: "address",
        indexed: true,
      },
    ],
    name: "RendererUpdated",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "tokenId",
        internalType: "uint256",
        type: "uint256",
        indexed: true,
      },
      {
        name: "seed",
        internalType: "bytes32",
        type: "bytes32",
        indexed: false,
      },
    ],
    name: "SeedFulfilled",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "currency",
        internalType: "address",
        type: "address",
        indexed: true,
      },
    ],
    name: "SupportedCurrencyAdded",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "currency",
        internalType: "address",
        type: "address",
        indexed: true,
      },
    ],
    name: "SupportedCurrencyRemoved",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "owner",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "tokenId",
        internalType: "uint256",
        type: "uint256",
        indexed: true,
      },
      {
        name: "mintPrice",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "TokenRedeemed",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "minter",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "tokenId",
        internalType: "uint256",
        type: "uint256",
        indexed: true,
      },
      {
        name: "newTokenId",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "TokenRerolled",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      { name: "from", internalType: "address", type: "address", indexed: true },
      { name: "to", internalType: "address", type: "address", indexed: true },
      {
        name: "tokenId",
        internalType: "uint256",
        type: "uint256",
        indexed: true,
      },
    ],
    name: "Transfer",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "oldAdmin",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "newAdmin",
        internalType: "address",
        type: "address",
        indexed: true,
      },
    ],
    name: "TransferAdmin",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "account",
        internalType: "address",
        type: "address",
        indexed: false,
      },
    ],
    name: "Unpaused",
  },
  {
    type: "error",
    inputs: [
      { name: "admin", internalType: "address", type: "address" },
      { name: "caller", internalType: "address", type: "address" },
    ],
    name: "AdminableUnauthorizedAccount",
  },
  { type: "error", inputs: [], name: "ERC721EnumerableForbiddenBatchMint" },
  {
    type: "error",
    inputs: [
      { name: "sender", internalType: "address", type: "address" },
      { name: "tokenId", internalType: "uint256", type: "uint256" },
      { name: "owner", internalType: "address", type: "address" },
    ],
    name: "ERC721IncorrectOwner",
  },
  {
    type: "error",
    inputs: [
      { name: "operator", internalType: "address", type: "address" },
      { name: "tokenId", internalType: "uint256", type: "uint256" },
    ],
    name: "ERC721InsufficientApproval",
  },
  {
    type: "error",
    inputs: [{ name: "approver", internalType: "address", type: "address" }],
    name: "ERC721InvalidApprover",
  },
  {
    type: "error",
    inputs: [{ name: "operator", internalType: "address", type: "address" }],
    name: "ERC721InvalidOperator",
  },
  {
    type: "error",
    inputs: [{ name: "owner", internalType: "address", type: "address" }],
    name: "ERC721InvalidOwner",
  },
  {
    type: "error",
    inputs: [{ name: "receiver", internalType: "address", type: "address" }],
    name: "ERC721InvalidReceiver",
  },
  {
    type: "error",
    inputs: [{ name: "sender", internalType: "address", type: "address" }],
    name: "ERC721InvalidSender",
  },
  {
    type: "error",
    inputs: [{ name: "tokenId", internalType: "uint256", type: "uint256" }],
    name: "ERC721NonexistentToken",
  },
  {
    type: "error",
    inputs: [
      { name: "owner", internalType: "address", type: "address" },
      { name: "index", internalType: "uint256", type: "uint256" },
    ],
    name: "ERC721OutOfBoundsIndex",
  },
  { type: "error", inputs: [], name: "EnforcedPause" },
  { type: "error", inputs: [], name: "ExpectedPause" },
  { type: "error", inputs: [], name: "FailedCall" },
  {
    type: "error",
    inputs: [
      { name: "balance", internalType: "uint256", type: "uint256" },
      { name: "needed", internalType: "uint256", type: "uint256" },
    ],
    name: "InsufficientBalance",
  },
  {
    type: "error",
    inputs: [{ name: "owner", internalType: "address", type: "address" }],
    name: "OwnableInvalidOwner",
  },
  {
    type: "error",
    inputs: [{ name: "account", internalType: "address", type: "address" }],
    name: "OwnableUnauthorizedAccount",
  },
  { type: "error", inputs: [], name: "ProjectToken__AlreadyInitialized" },
  {
    type: "error",
    inputs: [{ name: "currency", internalType: "address", type: "address" }],
    name: "ProjectToken__CurrencyAlreadySupported",
  },
  {
    type: "error",
    inputs: [{ name: "currency", internalType: "address", type: "address" }],
    name: "ProjectToken__CurrencyNotSupported",
  },
  {
    type: "error",
    inputs: [
      { name: "provided", internalType: "uint256", type: "uint256" },
      { name: "required", internalType: "uint256", type: "uint256" },
    ],
    name: "ProjectToken__InsufficientFee",
  },
  { type: "error", inputs: [], name: "ProjectToken__InsufficientSupply" },
  {
    type: "error",
    inputs: [{ name: "currency", internalType: "address", type: "address" }],
    name: "ProjectToken__InvalidCurrency",
  },
  { type: "error", inputs: [], name: "ProjectToken__InvalidFeeReceiver" },
  { type: "error", inputs: [], name: "ProjectToken__InvalidFeeSplit" },
  { type: "error", inputs: [], name: "ProjectToken__MaxSupplyMismatch" },
  {
    type: "error",
    inputs: [{ name: "tokenId", internalType: "uint256", type: "uint256" }],
    name: "ProjectToken__MetadataAlreadyLocked",
  },
  { type: "error", inputs: [], name: "ProjectToken__NotCreator" },
  { type: "error", inputs: [], name: "ProjectToken__PaymentFailed" },
  { type: "error", inputs: [], name: "ProjectToken__UnexpectedETH" },
  {
    type: "error",
    inputs: [{ name: "token", internalType: "address", type: "address" }],
    name: "SafeERC20FailedOperation",
  },
] as const

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// TezAirdrop
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const tezAirdropAbi = [
  {
    type: "constructor",
    inputs: [
      { name: "_owner", internalType: "address", type: "address" },
      { name: "_fxToken", internalType: "address", type: "address" },
      { name: "_signer", internalType: "address", type: "address" },
      { name: "_merkleRoot", internalType: "bytes32", type: "bytes32" },
      { name: "_lockTime", internalType: "uint256", type: "uint256" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [],
    name: "TEZ_WALLET_TYPEHASH",
    outputs: [{ name: "", internalType: "bytes32", type: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "_amount", internalType: "uint256", type: "uint256" },
      { name: "_wallet", internalType: "string", type: "string" },
      { name: "_signature", internalType: "bytes", type: "bytes" },
      { name: "_merkleProof", internalType: "bytes32[]", type: "bytes32[]" },
    ],
    name: "claim",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "_user", internalType: "address", type: "address" },
      { name: "_amount", internalType: "uint256", type: "uint256" },
      { name: "_wallet", internalType: "string", type: "string" },
      { name: "_signature", internalType: "bytes", type: "bytes" },
      { name: "_merkleProof", internalType: "bytes32[]", type: "bytes32[]" },
    ],
    name: "claimFor",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "_to", internalType: "address", type: "address" },
      { name: "_amount", internalType: "uint256", type: "uint256" },
      { name: "_wallet", internalType: "string", type: "string" },
      { name: "_signature", internalType: "bytes", type: "bytes" },
      { name: "_merkleProof", internalType: "bytes32[]", type: "bytes32[]" },
    ],
    name: "claimTo",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [],
    name: "eip712Domain",
    outputs: [
      { name: "fields", internalType: "bytes1", type: "bytes1" },
      { name: "name", internalType: "string", type: "string" },
      { name: "version", internalType: "string", type: "string" },
      { name: "chainId", internalType: "uint256", type: "uint256" },
      { name: "verifyingContract", internalType: "address", type: "address" },
      { name: "salt", internalType: "bytes32", type: "bytes32" },
      { name: "extensions", internalType: "uint256[]", type: "uint256[]" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "fxToken",
    outputs: [{ name: "", internalType: "address", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "_caller", internalType: "address", type: "address" },
      { name: "_wallet", internalType: "string", type: "string" },
    ],
    name: "generateTezWalletHash",
    outputs: [{ name: "", internalType: "bytes32", type: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [{ name: "", internalType: "string", type: "string" }],
    name: "hasClaimed",
    outputs: [{ name: "", internalType: "bool", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "lockTimestamp",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "merkleRoot",
    outputs: [{ name: "", internalType: "bytes32", type: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "owner",
    outputs: [{ name: "", internalType: "address", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "renounceOwnership",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [],
    name: "signer",
    outputs: [{ name: "", internalType: "address", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [{ name: "newOwner", internalType: "address", type: "address" }],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "_newTimestamp", internalType: "uint256", type: "uint256" },
    ],
    name: "updateLockTimestamp",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [{ name: "_newRoot", internalType: "bytes32", type: "bytes32" }],
    name: "updateMerkleRoot",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [{ name: "_newSigner", internalType: "address", type: "address" }],
    name: "updateSigner",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [{ name: "_to", internalType: "address", type: "address" }],
    name: "withdraw",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      { name: "user", internalType: "address", type: "address", indexed: true },
      { name: "wallet", internalType: "string", type: "string", indexed: true },
      {
        name: "amount",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "AirdropClaimed",
  },
  { type: "event", anonymous: false, inputs: [], name: "EIP712DomainChanged" },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "newTimestamp",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "LockTimestampUpdated",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "newRoot",
        internalType: "bytes32",
        type: "bytes32",
        indexed: false,
      },
    ],
    name: "MerkleRootUpdated",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "previousOwner",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "newOwner",
        internalType: "address",
        type: "address",
        indexed: true,
      },
    ],
    name: "OwnershipTransferred",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "newSigner",
        internalType: "address",
        type: "address",
        indexed: false,
      },
    ],
    name: "SignerUpdated",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      { name: "to", internalType: "address", type: "address", indexed: false },
      {
        name: "amount",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "Withdrawal",
  },
  { type: "error", inputs: [], name: "ECDSAInvalidSignature" },
  {
    type: "error",
    inputs: [{ name: "length", internalType: "uint256", type: "uint256" }],
    name: "ECDSAInvalidSignatureLength",
  },
  {
    type: "error",
    inputs: [{ name: "s", internalType: "bytes32", type: "bytes32" }],
    name: "ECDSAInvalidSignatureS",
  },
  { type: "error", inputs: [], name: "InvalidShortString" },
  {
    type: "error",
    inputs: [{ name: "owner", internalType: "address", type: "address" }],
    name: "OwnableInvalidOwner",
  },
  {
    type: "error",
    inputs: [{ name: "account", internalType: "address", type: "address" }],
    name: "OwnableUnauthorizedAccount",
  },
  {
    type: "error",
    inputs: [{ name: "token", internalType: "address", type: "address" }],
    name: "SafeERC20FailedOperation",
  },
  {
    type: "error",
    inputs: [{ name: "str", internalType: "string", type: "string" }],
    name: "StringTooLong",
  },
  { type: "error", inputs: [], name: "TezAirdrop__AlreadyClaimed" },
  { type: "error", inputs: [], name: "TezAirdrop__InvalidProof" },
  { type: "error", inputs: [], name: "TezAirdrop__InvalidSignature" },
  { type: "error", inputs: [], name: "TezAirdrop__LockTimeElapsed" },
  { type: "error", inputs: [], name: "TezAirdrop__LockTimeNotElapsed" },
  { type: "error", inputs: [], name: "TezAirdrop__ZeroAmount" },
] as const

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// TokenLaunchpad
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const tokenLaunchpadAbi = [
  {
    type: "constructor",
    inputs: [
      { name: "_fxToken", internalType: "address", type: "address" },
      { name: "_migrator", internalType: "address", type: "address" },
      { name: "_uniswapFactory", internalType: "address", type: "address" },
      { name: "_lockerFactory", internalType: "address", type: "address" },
      { name: "_initialOwner", internalType: "address", type: "address" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [],
    name: "DEFAULT_ADMIN_ROLE",
    outputs: [{ name: "", internalType: "bytes32", type: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "INITIAL_FEE_PERCENTAGE",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "INITIAL_FX_RATE",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "INITIAL_K",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "INITIAL_MAX_GRADUATION_RESERVE",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "INITIAL_MIN_SEED_AMOUNT",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "INITIAL_SUPPLY",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "LAUNCHER_ROLE",
    outputs: [{ name: "", internalType: "bytes32", type: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "MAX_FEE_PERCENTAGE",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "_creatorToken", internalType: "address", type: "address" },
      { name: "_amountIn", internalType: "uint256", type: "uint256" },
    ],
    name: "buy",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [{ name: "", internalType: "address", type: "address" }],
    name: "creatorTokenInfo",
    outputs: [
      { name: "user", internalType: "address", type: "address" },
      { name: "graduatedToken", internalType: "address", type: "address" },
      { name: "supply", internalType: "uint256", type: "uint256" },
      { name: "tradingEnabled", internalType: "bool", type: "bool" },
      { name: "isGraduated", internalType: "bool", type: "bool" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    name: "creatorTokens",
    outputs: [{ name: "", internalType: "address", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "feePercentage",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "feeReceiver",
    outputs: [{ name: "", internalType: "address", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "fxRate",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "fxToken",
    outputs: [{ name: "", internalType: "address", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "_creatorToken", internalType: "address", type: "address" },
      { name: "_amountIn", internalType: "uint256", type: "uint256" },
      {
        name: "_orderType",
        internalType: "enum ITokenLaunchpad.OrderType",
        type: "uint8",
      },
    ],
    name: "getAmountOut",
    outputs: [
      { name: "amountOut", internalType: "uint256", type: "uint256" },
      { name: "feeAmount", internalType: "uint256", type: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [{ name: "_user", internalType: "address", type: "address" }],
    name: "getCreatorTokens",
    outputs: [{ name: "", internalType: "address[]", type: "address[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "_offset", internalType: "uint256", type: "uint256" },
      { name: "_limit", internalType: "uint256", type: "uint256" },
    ],
    name: "getCreatorTokensPaginated",
    outputs: [
      { name: "tokens", internalType: "address[]", type: "address[]" },
      { name: "total", internalType: "uint256", type: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "_creatorToken", internalType: "address", type: "address" },
    ],
    name: "getGraduatedToken",
    outputs: [
      { name: "graduatedToken", internalType: "address", type: "address" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [{ name: "role", internalType: "bytes32", type: "bytes32" }],
    name: "getRoleAdmin",
    outputs: [{ name: "", internalType: "bytes32", type: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "_creatorToken", internalType: "address", type: "address" },
    ],
    name: "getTokenReserves",
    outputs: [
      { name: "", internalType: "uint256", type: "uint256" },
      { name: "", internalType: "uint256", type: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "getTotalCreatorTokens",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "getTotalUsers",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "_user", internalType: "address", type: "address" },
      { name: "_offset", internalType: "uint256", type: "uint256" },
      { name: "_limit", internalType: "uint256", type: "uint256" },
    ],
    name: "getUserTokensPaginated",
    outputs: [
      { name: "tokens", internalType: "address[]", type: "address[]" },
      { name: "total", internalType: "uint256", type: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "_creatorToken", internalType: "address", type: "address" },
    ],
    name: "graduate",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [{ name: "_launcher", internalType: "address", type: "address" }],
    name: "grantLauncherRole",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "role", internalType: "bytes32", type: "bytes32" },
      { name: "account", internalType: "address", type: "address" },
    ],
    name: "grantRole",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "role", internalType: "bytes32", type: "bytes32" },
      { name: "account", internalType: "address", type: "address" },
    ],
    name: "hasRole",
    outputs: [{ name: "", internalType: "bool", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "initialSupply",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "_creatorToken", internalType: "address", type: "address" },
    ],
    name: "isEligibleForGraduation",
    outputs: [
      { name: "", internalType: "enum ITokenLaunchpad.Status", type: "uint8" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "k",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "_name", internalType: "string", type: "string" },
      { name: "_symbol", internalType: "string", type: "string" },
      { name: "_totalFxAmountIn", internalType: "uint256", type: "uint256" },
    ],
    name: "launch",
    outputs: [
      { name: "creatorToken", internalType: "address", type: "address" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "_creator", internalType: "address", type: "address" },
      { name: "_name", internalType: "string", type: "string" },
      { name: "_symbol", internalType: "string", type: "string" },
      { name: "_totalFxAmountIn", internalType: "uint256", type: "uint256" },
    ],
    name: "launchFor",
    outputs: [
      { name: "creatorToken", internalType: "address", type: "address" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [],
    name: "lockerFactory",
    outputs: [
      {
        name: "",
        internalType: "contract IUniswapV2LockerFactory",
        type: "address",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "maxGraduationReserve",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "_creatorToken", internalType: "address", type: "address" },
    ],
    name: "migrate",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "_creatorToken", internalType: "address", type: "address" },
      { name: "_user", internalType: "address", type: "address" },
    ],
    name: "migrateFor",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [],
    name: "minSeedAmount",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "owner",
    outputs: [{ name: "", internalType: "address", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "pause",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [],
    name: "paused",
    outputs: [{ name: "", internalType: "bool", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [{ name: "", internalType: "address", type: "address" }],
    name: "poolInfo",
    outputs: [
      { name: "creatorReserve", internalType: "uint256", type: "uint256" },
      { name: "fxReserve", internalType: "uint256", type: "uint256" },
      { name: "k", internalType: "uint256", type: "uint256" },
      { name: "feePercentage", internalType: "uint256", type: "uint256" },
      { name: "feeReceiver", internalType: "address", type: "address" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "_desiredAmountOut", internalType: "uint256", type: "uint256" },
    ],
    name: "previewLaunch",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "renounceOwnership",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "role", internalType: "bytes32", type: "bytes32" },
      { name: "callerConfirmation", internalType: "address", type: "address" },
    ],
    name: "renounceRole",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [{ name: "_launcher", internalType: "address", type: "address" }],
    name: "revokeLauncherRole",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "role", internalType: "bytes32", type: "bytes32" },
      { name: "account", internalType: "address", type: "address" },
    ],
    name: "revokeRole",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "_creatorToken", internalType: "address", type: "address" },
      { name: "_amountIn", internalType: "uint256", type: "uint256" },
    ],
    name: "sell",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "_newPercentage", internalType: "uint256", type: "uint256" },
    ],
    name: "setFeePercentage",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "_newReceiver", internalType: "address", type: "address" },
    ],
    name: "setFeeReceiver",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [{ name: "_newRate", internalType: "uint256", type: "uint256" }],
    name: "setFxRate",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [{ name: "_newSupply", internalType: "uint256", type: "uint256" }],
    name: "setInitialSupply",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [{ name: "_newK", internalType: "uint256", type: "uint256" }],
    name: "setK",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [{ name: "_newReserve", internalType: "uint256", type: "uint256" }],
    name: "setMaxGraduationReserve",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [{ name: "_newAmount", internalType: "uint256", type: "uint256" }],
    name: "setMinSeedAmount",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [{ name: "interfaceId", internalType: "bytes4", type: "bytes4" }],
    name: "supportsInterface",
    outputs: [{ name: "", internalType: "bool", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [{ name: "newOwner", internalType: "address", type: "address" }],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [],
    name: "uniswapFactory",
    outputs: [
      { name: "", internalType: "contract IUniswapV2Factory", type: "address" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "uniswapMigrator",
    outputs: [
      {
        name: "",
        internalType: "contract IUniswapV2Migrator",
        type: "address",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "unpause",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    name: "users",
    outputs: [{ name: "", internalType: "address", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "creatorToken",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "feeReceiver",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "feeAmount",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "FeeCollected",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "feePercentage",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "FeePercentageUpdated",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "feeReceiver",
        internalType: "address",
        type: "address",
        indexed: true,
      },
    ],
    name: "FeeReceiverUpdated",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "fxRate",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "FxRateUpdated",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "creatorToken",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "graduatedToken",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "creatorLiquidity",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
      {
        name: "fxLiquidity",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "Graduated",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "initialSupply",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "InitialSupplyUpdated",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      { name: "k", internalType: "uint256", type: "uint256", indexed: false },
    ],
    name: "KUpdated",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      { name: "user", internalType: "address", type: "address", indexed: true },
      {
        name: "creatorToken",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "graduatedToken",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      { name: "id", internalType: "uint256", type: "uint256", indexed: false },
      { name: "name", internalType: "string", type: "string", indexed: false },
      {
        name: "symbol",
        internalType: "string",
        type: "string",
        indexed: false,
      },
    ],
    name: "Launched",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "creatorToken",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      { name: "pair", internalType: "address", type: "address", indexed: true },
      {
        name: "locker",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "liquidity",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "LockerCreated",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "maxGraduationReserve",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "MaxGraduationReserveUpdated",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      { name: "user", internalType: "address", type: "address", indexed: true },
      {
        name: "creatorToken",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "graduatedToken",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "amount",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "Migrated",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "minSeedAmount",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "MinSeedAmountUpdated",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "previousOwner",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "newOwner",
        internalType: "address",
        type: "address",
        indexed: true,
      },
    ],
    name: "OwnershipTransferred",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "account",
        internalType: "address",
        type: "address",
        indexed: false,
      },
    ],
    name: "Paused",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "creatorToken",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "feeReceiver",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "creatorReserve",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
      {
        name: "fxReserve",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
      { name: "k", internalType: "uint256", type: "uint256", indexed: false },
      {
        name: "feeAmount",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "PoolInitialized",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "creatorToken",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "creatorReserve",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
      {
        name: "fxReserve",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "PoolUpdated",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "creatorToken",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "sender",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "recipient",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "amountIn",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
      {
        name: "amountOut",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
      {
        name: "feeAmount",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "Purchased",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      { name: "role", internalType: "bytes32", type: "bytes32", indexed: true },
      {
        name: "previousAdminRole",
        internalType: "bytes32",
        type: "bytes32",
        indexed: true,
      },
      {
        name: "newAdminRole",
        internalType: "bytes32",
        type: "bytes32",
        indexed: true,
      },
    ],
    name: "RoleAdminChanged",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      { name: "role", internalType: "bytes32", type: "bytes32", indexed: true },
      {
        name: "account",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "sender",
        internalType: "address",
        type: "address",
        indexed: true,
      },
    ],
    name: "RoleGranted",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      { name: "role", internalType: "bytes32", type: "bytes32", indexed: true },
      {
        name: "account",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "sender",
        internalType: "address",
        type: "address",
        indexed: true,
      },
    ],
    name: "RoleRevoked",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "creatorToken",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "sender",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "recipient",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "amountIn",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
      {
        name: "amountOut",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
      {
        name: "feeAmount",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "Sold",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "account",
        internalType: "address",
        type: "address",
        indexed: false,
      },
    ],
    name: "Unpaused",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      { name: "user", internalType: "address", type: "address", indexed: true },
    ],
    name: "UserCreated",
  },
  { type: "error", inputs: [], name: "AccessControlBadConfirmation" },
  {
    type: "error",
    inputs: [
      { name: "account", internalType: "address", type: "address" },
      { name: "neededRole", internalType: "bytes32", type: "bytes32" },
    ],
    name: "AccessControlUnauthorizedAccount",
  },
  { type: "error", inputs: [], name: "EnforcedPause" },
  { type: "error", inputs: [], name: "ExpectedPause" },
  {
    type: "error",
    inputs: [{ name: "owner", internalType: "address", type: "address" }],
    name: "OwnableInvalidOwner",
  },
  {
    type: "error",
    inputs: [{ name: "account", internalType: "address", type: "address" }],
    name: "OwnableUnauthorizedAccount",
  },
  {
    type: "error",
    inputs: [{ name: "token", internalType: "address", type: "address" }],
    name: "SafeERC20FailedOperation",
  },
  { type: "error", inputs: [], name: "TokenLaunchpad__CalculationOverflow" },
  { type: "error", inputs: [], name: "TokenLaunchpad__FeeExceedsMaximum" },
  { type: "error", inputs: [], name: "TokenLaunchpad__InsufficientLiquidity" },
  { type: "error", inputs: [], name: "TokenLaunchpad__InvalidCreatorAddress" },
  {
    type: "error",
    inputs: [],
    name: "TokenLaunchpad__InvalidGraduationReserve",
  },
  { type: "error", inputs: [], name: "TokenLaunchpad__InvalidK" },
  { type: "error", inputs: [], name: "TokenLaunchpad__InvalidPurchaseAmount" },
  { type: "error", inputs: [], name: "TokenLaunchpad__InvalidRate" },
  { type: "error", inputs: [], name: "TokenLaunchpad__InvalidSeedAmount" },
  { type: "error", inputs: [], name: "TokenLaunchpad__InvalidSupply" },
  { type: "error", inputs: [], name: "TokenLaunchpad__NoTokensToMigrate" },
  { type: "error", inputs: [], name: "TokenLaunchpad__NotTokenCreator" },
  { type: "error", inputs: [], name: "TokenLaunchpad__TokenNotGraduated" },
  { type: "error", inputs: [], name: "TokenLaunchpad__TokenNotLaunched" },
  { type: "error", inputs: [], name: "TokenLaunchpad__TradingNotEnabled" },
  { type: "error", inputs: [], name: "TokenLaunchpad__ZeroAddress" },
  { type: "error", inputs: [], name: "TokenLaunchpad__ZeroAmountIn" },
] as const
