//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// DutchAuctionV2
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const dutchAuctionV2Abi = [
  {
    type: "constructor",
    inputs: [
      { name: "_owner", internalType: "address", type: "address" },
      { name: "_feeManager", internalType: "address", type: "address" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "", internalType: "address", type: "address" },
      { name: "", internalType: "uint256", type: "uint256" },
    ],
    name: "auctions",
    outputs: [
      { name: "refunded", internalType: "bool", type: "bool" },
      { name: "stepLength", internalType: "uint248", type: "uint248" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "_token", internalType: "address", type: "address" },
      { name: "_reserveId", internalType: "uint256", type: "uint256" },
      { name: "_amount", internalType: "uint256", type: "uint256" },
      { name: "_to", internalType: "address", type: "address" },
    ],
    name: "buy",
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    inputs: [
      { name: "_token", internalType: "address", type: "address" },
      { name: "_reserveId", internalType: "uint256", type: "uint256" },
      { name: "_to", internalType: "address", type: "address" },
      { name: "_indexes", internalType: "uint256[]", type: "uint256[]" },
      { name: "_proofs", internalType: "bytes32[][]", type: "bytes32[][]" },
    ],
    name: "buyAllowlist",
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    inputs: [
      { name: "_token", internalType: "address", type: "address" },
      { name: "_reserveId", internalType: "uint256", type: "uint256" },
      { name: "_amount", internalType: "uint256", type: "uint256" },
      { name: "_to", internalType: "address", type: "address" },
      { name: "_index", internalType: "uint256", type: "uint256" },
      { name: "_signature", internalType: "bytes", type: "bytes" },
    ],
    name: "buyMintPass",
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    inputs: [],
    name: "cancelOwnershipHandover",
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    inputs: [
      { name: "pendingOwner", internalType: "address", type: "address" },
    ],
    name: "completeOwnershipHandover",
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    inputs: [],
    name: "eip712Domain",
    outputs: [
      { name: "fields", internalType: "bytes1", type: "bytes1" },
      { name: "name", internalType: "string", type: "string" },
      { name: "version", internalType: "string", type: "string" },
      { name: "chainId", internalType: "uint256", type: "uint256" },
      { name: "verifyingContract", internalType: "address", type: "address" },
      { name: "salt", internalType: "bytes32", type: "bytes32" },
      { name: "extensions", internalType: "uint256[]", type: "uint256[]" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "feeManager",
    outputs: [{ name: "", internalType: "address", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "_token", internalType: "address", type: "address" },
      { name: "_reserveId", internalType: "uint256", type: "uint256" },
      { name: "_reserveNonce", internalType: "uint256", type: "uint256" },
      { name: "_index", internalType: "uint256", type: "uint256" },
      { name: "_claimer", internalType: "address", type: "address" },
    ],
    name: "generateTypedDataHash",
    outputs: [{ name: "", internalType: "bytes32", type: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [{ name: "_token", internalType: "address", type: "address" }],
    name: "getFirstValidReserve",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [{ name: "_token", internalType: "address", type: "address" }],
    name: "getLatestUpdate",
    outputs: [{ name: "", internalType: "uint40", type: "uint40" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "_token", internalType: "address", type: "address" },
      { name: "_reserveId", internalType: "uint256", type: "uint256" },
    ],
    name: "getPrice",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "", internalType: "address", type: "address" },
      { name: "", internalType: "uint256", type: "uint256" },
    ],
    name: "merkleRoots",
    outputs: [{ name: "", internalType: "bytes32", type: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "", internalType: "address", type: "address" },
      { name: "", internalType: "uint256", type: "uint256" },
    ],
    name: "numberMinted",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "owner",
    outputs: [{ name: "result", internalType: "address", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "pendingOwner", internalType: "address", type: "address" },
    ],
    name: "ownershipHandoverExpiresAt",
    outputs: [{ name: "result", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "pause",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [],
    name: "paused",
    outputs: [{ name: "", internalType: "bool", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "_token", internalType: "address", type: "address" },
      { name: "_reserveId", internalType: "uint256", type: "uint256" },
      { name: "_buyer", internalType: "address", type: "address" },
    ],
    name: "refund",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "", internalType: "address", type: "address" },
      { name: "", internalType: "uint256", type: "uint256" },
    ],
    name: "refunds",
    outputs: [{ name: "lastPrice", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "renounceOwnership",
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    inputs: [],
    name: "requestOwnershipHandover",
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    inputs: [
      { name: "", internalType: "address", type: "address" },
      { name: "", internalType: "uint256", type: "uint256" },
    ],
    name: "reserveNonce",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "", internalType: "address", type: "address" },
      { name: "", internalType: "uint256", type: "uint256" },
    ],
    name: "reserves",
    outputs: [
      { name: "startTime", internalType: "uint64", type: "uint64" },
      { name: "endTime", internalType: "uint64", type: "uint64" },
      { name: "allocation", internalType: "uint128", type: "uint128" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "", internalType: "address", type: "address" },
      { name: "", internalType: "uint256", type: "uint256" },
    ],
    name: "saleProceeds",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [{ name: "_feeManager", internalType: "address", type: "address" }],
    name: "setFeeManager",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      {
        name: "_reserve",
        internalType: "struct ReserveInfo",
        type: "tuple",
        components: [
          { name: "startTime", internalType: "uint64", type: "uint64" },
          { name: "endTime", internalType: "uint64", type: "uint64" },
          { name: "allocation", internalType: "uint128", type: "uint128" },
        ],
      },
      { name: "_mintDetails", internalType: "bytes", type: "bytes" },
    ],
    name: "setMintDetails",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "", internalType: "address", type: "address" },
      { name: "", internalType: "uint256", type: "uint256" },
    ],
    name: "signingAuthorities",
    outputs: [{ name: "", internalType: "address", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [{ name: "newOwner", internalType: "address", type: "address" }],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    inputs: [],
    name: "unpause",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "_token", internalType: "address", type: "address" },
      { name: "_reserveId", internalType: "uint256", type: "uint256" },
    ],
    name: "withdraw",
    outputs: [],
    stateMutability: "nonpayable",
  },
  { type: "event", anonymous: false, inputs: [], name: "EIP712DomainChanged" },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "_prevManager",
        internalType: "address",
        type: "address",
        indexed: false,
      },
      {
        name: "_newManager",
        internalType: "address",
        type: "address",
        indexed: false,
      },
    ],
    name: "FeeManagerSet",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "_token",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "_reserveId",
        internalType: "uint256",
        type: "uint256",
        indexed: true,
      },
      {
        name: "_reserveInfo",
        internalType: "struct ReserveInfo",
        type: "tuple",
        components: [
          { name: "startTime", internalType: "uint64", type: "uint64" },
          { name: "endTime", internalType: "uint64", type: "uint64" },
          { name: "allocation", internalType: "uint128", type: "uint128" },
        ],
        indexed: false,
      },
      {
        name: "_merkleRoot",
        internalType: "bytes32",
        type: "bytes32",
        indexed: false,
      },
      {
        name: "_mintPassSigner",
        internalType: "address",
        type: "address",
        indexed: false,
      },
      {
        name: "_auctionInfo",
        internalType: "struct AuctionInfo",
        type: "tuple",
        components: [
          { name: "refunded", internalType: "bool", type: "bool" },
          { name: "stepLength", internalType: "uint248", type: "uint248" },
          { name: "prices", internalType: "uint256[]", type: "uint256[]" },
        ],
        indexed: false,
      },
    ],
    name: "MintDetailsSet",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "pendingOwner",
        internalType: "address",
        type: "address",
        indexed: true,
      },
    ],
    name: "OwnershipHandoverCanceled",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "pendingOwner",
        internalType: "address",
        type: "address",
        indexed: true,
      },
    ],
    name: "OwnershipHandoverRequested",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "oldOwner",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "newOwner",
        internalType: "address",
        type: "address",
        indexed: true,
      },
    ],
    name: "OwnershipTransferred",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "_token",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "_reserveId",
        internalType: "uint256",
        type: "uint256",
        indexed: true,
      },
      {
        name: "_claimer",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "_index",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "PassClaimed",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "account",
        internalType: "address",
        type: "address",
        indexed: false,
      },
    ],
    name: "Paused",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "_token",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "_reserveId",
        internalType: "uint256",
        type: "uint256",
        indexed: true,
      },
      {
        name: "_buyer",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      { name: "_to", internalType: "address", type: "address", indexed: false },
      {
        name: "_amount",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
      {
        name: "_price",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
      {
        name: "_platformFee",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
      {
        name: "_mintFee",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
      {
        name: "_splitAmount",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "Purchase",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "_token",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "_reserveId",
        internalType: "uint256",
        type: "uint256",
        indexed: true,
      },
      {
        name: "_buyer",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "_refundAmount",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "RefundClaimed",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "_token",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "_reserveId",
        internalType: "uint256",
        type: "uint256",
        indexed: true,
      },
      {
        name: "_claimer",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "_index",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "SlotClaimed",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "account",
        internalType: "address",
        type: "address",
        indexed: false,
      },
    ],
    name: "Unpaused",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "_token",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "_reserveId",
        internalType: "uint256",
        type: "uint256",
        indexed: true,
      },
      {
        name: "_creator",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "_proceeds",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "Withdrawn",
  },
  { type: "error", inputs: [], name: "AddressZero" },
  { type: "error", inputs: [], name: "InsufficientFunds" },
  { type: "error", inputs: [], name: "InsufficientPrice" },
  { type: "error", inputs: [], name: "InvalidAllocation" },
  { type: "error", inputs: [], name: "InvalidAmount" },
  { type: "error", inputs: [], name: "InvalidPayment" },
  { type: "error", inputs: [], name: "InvalidPrice" },
  { type: "error", inputs: [], name: "InvalidPriceCurve" },
  { type: "error", inputs: [], name: "InvalidProof" },
  { type: "error", inputs: [], name: "InvalidReserve" },
  { type: "error", inputs: [], name: "InvalidShortString" },
  { type: "error", inputs: [], name: "InvalidSignature" },
  { type: "error", inputs: [], name: "InvalidStep" },
  { type: "error", inputs: [], name: "InvalidToken" },
  { type: "error", inputs: [], name: "NewOwnerIsZeroAddress" },
  { type: "error", inputs: [], name: "NoAllowlist" },
  { type: "error", inputs: [], name: "NoHandoverRequest" },
  { type: "error", inputs: [], name: "NoPublicMint" },
  { type: "error", inputs: [], name: "NoRefund" },
  { type: "error", inputs: [], name: "NoSigningAuthority" },
  { type: "error", inputs: [], name: "NonRefundableDA" },
  { type: "error", inputs: [], name: "NotEnded" },
  { type: "error", inputs: [], name: "NotStarted" },
  { type: "error", inputs: [], name: "OnlyAuthorityOrAllowlist" },
  { type: "error", inputs: [], name: "PassAlreadyClaimed" },
  { type: "error", inputs: [], name: "PricesOutOfOrder" },
  { type: "error", inputs: [], name: "SlotAlreadyClaimed" },
  {
    type: "error",
    inputs: [{ name: "str", internalType: "string", type: "string" }],
    name: "StringTooLong",
  },
  { type: "error", inputs: [], name: "Unauthorized" },
] as const
