export const FEE_MANAGER_V1 = [
  {
    inputs: [
      { internalType: "address", name: "_owner", type: "address" },
      { internalType: "uint120", name: "_platformFee", type: "uint120" },
      { internalType: "uint64", name: "_mintPercentage", type: "uint64" },
      { internalType: "uint64", name: "_splitPercentage", type: "uint64" },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  { inputs: [], name: "InvalidPercentage", type: "error" },
  { inputs: [], name: "NewOwnerIsZeroAddress", type: "error" },
  { inputs: [], name: "NoHandoverRequest", type: "error" },
  { inputs: [], name: "Unauthorized", type: "error" },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "_token",
        type: "address",
      },
      { indexed: false, internalType: "bool", name: "_enabled", type: "bool" },
      {
        indexed: false,
        internalType: "uint120",
        name: "_platformFee",
        type: "uint120",
      },
      {
        indexed: false,
        internalType: "uint64",
        name: "_mintPercentage",
        type: "uint64",
      },
      {
        indexed: false,
        internalType: "uint64",
        name: "_splitPercentage",
        type: "uint64",
      },
    ],
    name: "CustomFeesUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint120",
        name: "_platformFee",
        type: "uint120",
      },
      {
        indexed: false,
        internalType: "uint64",
        name: "_mintPercentage",
        type: "uint64",
      },
      {
        indexed: false,
        internalType: "uint64",
        name: "_splitPercentage",
        type: "uint64",
      },
    ],
    name: "DefaultFeesUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "pendingOwner",
        type: "address",
      },
    ],
    name: "OwnershipHandoverCanceled",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "pendingOwner",
        type: "address",
      },
    ],
    name: "OwnershipHandoverRequested",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "oldOwner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "OwnershipTransferred",
    type: "event",
  },
  {
    inputs: [
      { internalType: "address", name: "_token", type: "address" },
      { internalType: "uint256", name: "_price", type: "uint256" },
      { internalType: "uint256", name: "_amount", type: "uint256" },
    ],
    name: "calculateFees",
    outputs: [
      { internalType: "uint256", name: "platformAmount", type: "uint256" },
      { internalType: "uint256", name: "mintAmount", type: "uint256" },
      { internalType: "uint256", name: "splitAmount", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "cancelOwnershipHandover",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "pendingOwner", type: "address" },
    ],
    name: "completeOwnershipHandover",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "customFees",
    outputs: [
      { internalType: "bool", name: "enabled", type: "bool" },
      { internalType: "uint120", name: "platformFee", type: "uint120" },
      { internalType: "uint64", name: "mintPercentage", type: "uint64" },
      { internalType: "uint64", name: "splitPercentage", type: "uint64" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_token", type: "address" }],
    name: "getFeeValues",
    outputs: [
      { internalType: "uint120", name: "", type: "uint120" },
      { internalType: "uint64", name: "", type: "uint64" },
      { internalType: "uint64", name: "", type: "uint64" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "mintPercentage",
    outputs: [{ internalType: "uint64", name: "", type: "uint64" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [{ internalType: "address", name: "result", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "pendingOwner", type: "address" },
    ],
    name: "ownershipHandoverExpiresAt",
    outputs: [{ internalType: "uint256", name: "result", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "platformFee",
    outputs: [{ internalType: "uint120", name: "", type: "uint120" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "renounceOwnership",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [],
    name: "requestOwnershipHandover",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_token", type: "address" },
      { internalType: "bool", name: "_enabled", type: "bool" },
      { internalType: "uint120", name: "_platformFee", type: "uint120" },
      { internalType: "uint64", name: "_mintPercentage", type: "uint64" },
      { internalType: "uint64", name: "_splitPercentage", type: "uint64" },
    ],
    name: "setCustomFees",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint120", name: "_platformFee", type: "uint120" },
      { internalType: "uint64", name: "_mintPercentage", type: "uint64" },
      { internalType: "uint64", name: "_splitPercentage", type: "uint64" },
    ],
    name: "setDefaultFees",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "splitPercentage",
    outputs: [{ internalType: "uint64", name: "", type: "uint64" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "newOwner", type: "address" }],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_to", type: "address" }],
    name: "withdraw",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  { stateMutability: "payable", type: "receive" },
]
