export const FX_TOKEN_LAUNCHPAD_ABI = [
  {
    type: "constructor",
    inputs: [
      { name: "_fxToken", internalType: "address", type: "address" },
      { name: "_migrator", internalType: "address", type: "address" },
      {
        name: "_uniswapFactory",
        internalType: "address",
        type: "address",
      },
      {
        name: "_lockerFactory",
        internalType: "address",
        type: "address",
      },
      { name: "_initialOwner", internalType: "address", type: "address" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [],
    name: "DEFAULT_ADMIN_ROLE",
    outputs: [{ name: "", internalType: "bytes32", type: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "INITIAL_FEE_PERCENTAGE",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "INITIAL_K",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "INITIAL_MAX_GRADUATION_RESERVE",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "INITIAL_MIN_SEED_AMOUNT",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "INITIAL_SUPPLY",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "LAUNCHER_ROLE",
    outputs: [{ name: "", internalType: "bytes32", type: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "MAX_FEE_PERCENTAGE",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "_creatorToken", internalType: "address", type: "address" },
      { name: "_amountIn", internalType: "uint256", type: "uint256" },
    ],
    name: "buy",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [{ name: "", internalType: "address", type: "address" }],
    name: "creatorTokenInfo",
    outputs: [
      { name: "user", internalType: "address", type: "address" },
      {
        name: "graduatedToken",
        internalType: "address",
        type: "address",
      },
      { name: "supply", internalType: "uint256", type: "uint256" },
      { name: "tradingEnabled", internalType: "bool", type: "bool" },
      { name: "isGraduated", internalType: "bool", type: "bool" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    name: "creatorTokens",
    outputs: [{ name: "", internalType: "address", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "feePercentage",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "feeReceiver",
    outputs: [{ name: "", internalType: "address", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "fxToken",
    outputs: [{ name: "", internalType: "address", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "_creatorToken", internalType: "address", type: "address" },
      { name: "_amountIn", internalType: "uint256", type: "uint256" },
      {
        name: "_orderType",
        internalType: "enum ITokenLaunchpad.OrderType",
        type: "uint8",
      },
    ],
    name: "getAmountOut",
    outputs: [
      { name: "amountOut", internalType: "uint256", type: "uint256" },
      { name: "feeAmount", internalType: "uint256", type: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [{ name: "_user", internalType: "address", type: "address" }],
    name: "getCreatorTokens",
    outputs: [{ name: "", internalType: "address[]", type: "address[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "_offset", internalType: "uint256", type: "uint256" },
      { name: "_limit", internalType: "uint256", type: "uint256" },
    ],
    name: "getCreatorTokensPaginated",
    outputs: [
      { name: "tokens", internalType: "address[]", type: "address[]" },
      { name: "total", internalType: "uint256", type: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "_creatorToken", internalType: "address", type: "address" },
    ],
    name: "getGraduatedToken",
    outputs: [
      { name: "graduatedToken", internalType: "address", type: "address" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [{ name: "role", internalType: "bytes32", type: "bytes32" }],
    name: "getRoleAdmin",
    outputs: [{ name: "", internalType: "bytes32", type: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "_creatorToken", internalType: "address", type: "address" },
    ],
    name: "getTokenReserves",
    outputs: [
      { name: "", internalType: "uint256", type: "uint256" },
      { name: "", internalType: "uint256", type: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "getTotalCreatorTokens",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "getTotalUsers",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "_user", internalType: "address", type: "address" },
      { name: "_offset", internalType: "uint256", type: "uint256" },
      { name: "_limit", internalType: "uint256", type: "uint256" },
    ],
    name: "getUserTokensPaginated",
    outputs: [
      { name: "tokens", internalType: "address[]", type: "address[]" },
      { name: "total", internalType: "uint256", type: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "_creatorToken", internalType: "address", type: "address" },
    ],
    name: "graduate",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [{ name: "_launcher", internalType: "address", type: "address" }],
    name: "grantLauncherRole",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "role", internalType: "bytes32", type: "bytes32" },
      { name: "account", internalType: "address", type: "address" },
    ],
    name: "grantRole",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "role", internalType: "bytes32", type: "bytes32" },
      { name: "account", internalType: "address", type: "address" },
    ],
    name: "hasRole",
    outputs: [{ name: "", internalType: "bool", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "initialSupply",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "_creatorToken", internalType: "address", type: "address" },
    ],
    name: "isEligibleForGraduation",
    outputs: [
      {
        name: "",
        internalType: "enum ITokenLaunchpad.Status",
        type: "uint8",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "k",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "_name", internalType: "string", type: "string" },
      { name: "_symbol", internalType: "string", type: "string" },
      {
        name: "_totalFxAmountIn",
        internalType: "uint256",
        type: "uint256",
      },
    ],
    name: "launch",
    outputs: [
      { name: "creatorToken", internalType: "address", type: "address" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "_creator", internalType: "address", type: "address" },
      { name: "_name", internalType: "string", type: "string" },
      { name: "_symbol", internalType: "string", type: "string" },
      {
        name: "_totalFxAmountIn",
        internalType: "uint256",
        type: "uint256",
      },
    ],
    name: "launchFor",
    outputs: [
      { name: "creatorToken", internalType: "address", type: "address" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [],
    name: "lockerFactory",
    outputs: [
      {
        name: "",
        internalType: "contract IUniswapV2LockerFactory",
        type: "address",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "maxGraduationReserve",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "_creatorToken", internalType: "address", type: "address" },
    ],
    name: "migrate",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "_creatorToken", internalType: "address", type: "address" },
      { name: "_user", internalType: "address", type: "address" },
    ],
    name: "migrateFor",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [],
    name: "minSeedAmount",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "owner",
    outputs: [{ name: "", internalType: "address", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "pause",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [],
    name: "paused",
    outputs: [{ name: "", internalType: "bool", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [{ name: "", internalType: "address", type: "address" }],
    name: "poolInfo",
    outputs: [
      {
        name: "creatorReserve",
        internalType: "uint256",
        type: "uint256",
      },
      { name: "fxReserve", internalType: "uint256", type: "uint256" },
      { name: "k", internalType: "uint256", type: "uint256" },
      { name: "feePercentage", internalType: "uint256", type: "uint256" },
      { name: "feeReceiver", internalType: "address", type: "address" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      {
        name: "_desiredAmountOut",
        internalType: "uint256",
        type: "uint256",
      },
    ],
    name: "previewLaunch",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "renounceOwnership",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "role", internalType: "bytes32", type: "bytes32" },
      {
        name: "callerConfirmation",
        internalType: "address",
        type: "address",
      },
    ],
    name: "renounceRole",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [{ name: "_launcher", internalType: "address", type: "address" }],
    name: "revokeLauncherRole",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "role", internalType: "bytes32", type: "bytes32" },
      { name: "account", internalType: "address", type: "address" },
    ],
    name: "revokeRole",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "_creatorToken", internalType: "address", type: "address" },
      { name: "_amountIn", internalType: "uint256", type: "uint256" },
    ],
    name: "sell",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "_newPercentage", internalType: "uint256", type: "uint256" },
    ],
    name: "setFeePercentage",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "_newReceiver", internalType: "address", type: "address" },
    ],
    name: "setFeeReceiver",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [{ name: "_newSupply", internalType: "uint256", type: "uint256" }],
    name: "setInitialSupply",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [{ name: "_newK", internalType: "uint256", type: "uint256" }],
    name: "setK",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [{ name: "_newReserve", internalType: "uint256", type: "uint256" }],
    name: "setMaxGraduationReserve",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [{ name: "_newAmount", internalType: "uint256", type: "uint256" }],
    name: "setMinSeedAmount",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [{ name: "interfaceId", internalType: "bytes4", type: "bytes4" }],
    name: "supportsInterface",
    outputs: [{ name: "", internalType: "bool", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [{ name: "newOwner", internalType: "address", type: "address" }],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [],
    name: "uniswapFactory",
    outputs: [
      {
        name: "",
        internalType: "contract IUniswapV2Factory",
        type: "address",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "uniswapMigrator",
    outputs: [
      {
        name: "",
        internalType: "contract IUniswapV2Migrator",
        type: "address",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "unpause",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    name: "users",
    outputs: [{ name: "", internalType: "address", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "creatorToken",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "feeReceiver",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "feeAmount",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "FeeCollected",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "feePercentage",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "FeePercentageUpdated",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "feeReceiver",
        internalType: "address",
        type: "address",
        indexed: true,
      },
    ],
    name: "FeeReceiverUpdated",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "creatorToken",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "graduatedToken",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "creatorLiquidity",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
      {
        name: "fxLiquidity",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "Graduated",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "initialSupply",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "InitialSupplyUpdated",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "k",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "KUpdated",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "user",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "creatorToken",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "graduatedToken",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "id",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
      {
        name: "name",
        internalType: "string",
        type: "string",
        indexed: false,
      },
      {
        name: "symbol",
        internalType: "string",
        type: "string",
        indexed: false,
      },
    ],
    name: "Launched",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "creatorToken",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "pair",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "locker",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "liquidity",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "LockerCreated",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "maxGraduationReserve",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "MaxGraduationReserveUpdated",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "user",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "creatorToken",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "graduatedToken",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "amount",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "Migrated",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "minSeedAmount",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "MinSeedAmountUpdated",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "previousOwner",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "newOwner",
        internalType: "address",
        type: "address",
        indexed: true,
      },
    ],
    name: "OwnershipTransferred",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "account",
        internalType: "address",
        type: "address",
        indexed: false,
      },
    ],
    name: "Paused",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "creatorToken",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "feeReceiver",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "creatorReserve",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
      {
        name: "fxReserve",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
      {
        name: "k",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
      {
        name: "feeAmount",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "PoolInitialized",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "creatorToken",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "creatorReserve",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
      {
        name: "fxReserve",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "PoolUpdated",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "creatorToken",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "sender",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "recipient",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "amountIn",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
      {
        name: "amountOut",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
      {
        name: "feeAmount",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "Purchased",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "role",
        internalType: "bytes32",
        type: "bytes32",
        indexed: true,
      },
      {
        name: "previousAdminRole",
        internalType: "bytes32",
        type: "bytes32",
        indexed: true,
      },
      {
        name: "newAdminRole",
        internalType: "bytes32",
        type: "bytes32",
        indexed: true,
      },
    ],
    name: "RoleAdminChanged",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "role",
        internalType: "bytes32",
        type: "bytes32",
        indexed: true,
      },
      {
        name: "account",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "sender",
        internalType: "address",
        type: "address",
        indexed: true,
      },
    ],
    name: "RoleGranted",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "role",
        internalType: "bytes32",
        type: "bytes32",
        indexed: true,
      },
      {
        name: "account",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "sender",
        internalType: "address",
        type: "address",
        indexed: true,
      },
    ],
    name: "RoleRevoked",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "creatorToken",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "sender",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "recipient",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "amountIn",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
      {
        name: "amountOut",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
      {
        name: "feeAmount",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "Sold",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "account",
        internalType: "address",
        type: "address",
        indexed: false,
      },
    ],
    name: "Unpaused",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "user",
        internalType: "address",
        type: "address",
        indexed: true,
      },
    ],
    name: "UserCreated",
  },
  { type: "error", inputs: [], name: "AccessControlBadConfirmation" },
  {
    type: "error",
    inputs: [
      { name: "account", internalType: "address", type: "address" },
      { name: "neededRole", internalType: "bytes32", type: "bytes32" },
    ],
    name: "AccessControlUnauthorizedAccount",
  },
  { type: "error", inputs: [], name: "EnforcedPause" },
  { type: "error", inputs: [], name: "ExpectedPause" },
  {
    type: "error",
    inputs: [{ name: "owner", internalType: "address", type: "address" }],
    name: "OwnableInvalidOwner",
  },
  {
    type: "error",
    inputs: [{ name: "account", internalType: "address", type: "address" }],
    name: "OwnableUnauthorizedAccount",
  },
  {
    type: "error",
    inputs: [{ name: "token", internalType: "address", type: "address" }],
    name: "SafeERC20FailedOperation",
  },
  {
    type: "error",
    inputs: [],
    name: "TokenLaunchpad__CalculationOverflow",
  },
  {
    type: "error",
    inputs: [],
    name: "TokenLaunchpad__FeeExceedsMaximum",
  },
  {
    type: "error",
    inputs: [],
    name: "TokenLaunchpad__InsufficientLiquidity",
  },
  {
    type: "error",
    inputs: [],
    name: "TokenLaunchpad__InvalidCreatorAddress",
  },
  {
    type: "error",
    inputs: [],
    name: "TokenLaunchpad__InvalidGraduation",
  },
  {
    type: "error",
    inputs: [],
    name: "TokenLaunchpad__InvalidGraduationReserve",
  },
  { type: "error", inputs: [], name: "TokenLaunchpad__InvalidK" },
  {
    type: "error",
    inputs: [],
    name: "TokenLaunchpad__InvalidPurchaseAmount",
  },
  { type: "error", inputs: [], name: "TokenLaunchpad__InvalidRate" },
  {
    type: "error",
    inputs: [],
    name: "TokenLaunchpad__InvalidSeedAmount",
  },
  { type: "error", inputs: [], name: "TokenLaunchpad__InvalidSupply" },
  {
    type: "error",
    inputs: [],
    name: "TokenLaunchpad__NoTokensToMigrate",
  },
  {
    type: "error",
    inputs: [],
    name: "TokenLaunchpad__TokenNotGraduated",
  },
  { type: "error", inputs: [], name: "TokenLaunchpad__TokenNotLaunched" },
  {
    type: "error",
    inputs: [],
    name: "TokenLaunchpad__TradingNotEnabled",
  },
  { type: "error", inputs: [], name: "TokenLaunchpad__ZeroAddress" },
  { type: "error", inputs: [], name: "TokenLaunchpad__ZeroAmountIn" },
]
